### ISSUE TITLE
ES6 polyfill.

### ISSUE THREAD

**Issue by cscott** [requirejs/requirejs#1028]
(Cross posted from https://gist.github.com/wycats/51c96e3adcdb3a68cbc3/#comment-1006744)

If you do something like:

``` js
function define(deps, f) {
  return Promise.all(deps.map(function(d) {
    return System.import(d);
  })).then(function() {
    return f.apply(null, arguments);
   });
}
```

you can obtain an AMD-style loader which works with ES6 modules.  There is already a polyfill for `Promise` in `es6-shim`.  It might be interesting to write a "polyfill" for `System.import` based on requirejs which used the definition of `define` above.  This would allow users to migrate to es6 without rewriting all of their modules.

This probably isn't the right bug tracker for this idea, but the `requirejs-es6shim` project doesn't exist yet. ;)

**Comment by Rush** [comment]
Just stumbled upon this discussion, what's the status today?

**Comment by jrburke** [comment]
The ES loader spec is still undefined. Latest work seems to be happening at https://whatwg.github.io/loader/ but I would not read too much into that spec right now. Still looks like very much a work in progress, very incomplete. I also expect they will want to revisit normalizing on URLs vs module IDs.
