### ISSUE TITLE
Multiple base url support

### ISSUE THREAD

**Issue by Virbhadrasinh** [requirejs/requirejs#1042]
I have two different application running on two different servers with their own requirejs configs. Application2 will use Application1 internally.

**Details of Application1** : It's running on //localhost:9000

Requirejs configuration

<pre>var require = {
        baseUrl : '/assets/resources',
        paths : {
              dateLib : 'libraries/dateLib/date'
        }
}</pre>

Module1 : Application Starter
<pre>
define(function(require) {
      var Utility = require('modules/commons/utility');

      var ApplicationStarter = Backbone.View.extend({
         initialize : function(options) {
            console.log('Inside ApplicationStarter initialize');
            new Utility(options); 
         }
      });
});
</pre>

Module2 : Utility

<pre>
define(function(require) {
      var Utility = Backbone.View.extend({
         initialize : function(options) {
            console.log('Inside Utility initialize');
         }
      });
});
</pre>

**Details of Application2** :  It's running on //localhost:9001

Requirejs configuration

<pre>var require = {
        baseUrl : '/assets',
        paths : {
              jqueryui : 'libraries/jquery-ui/js/jquery-ui'
        }
}</pre>

Module1 : Boot Loader
<pre>
define(function(require) {
      var Helper = require('modules/helper/helper');       
      var ApplicationStarter = require('//localhost:9000/assets/resources/modules/applicationstarter');

      var BootLoader = Backbone.View.extend({
         initialize : function(options) {
            console.log('Inside BootLoader initialize');
            new Helper(options); 
            new ApplicationStarter(options); 
         }
      });
});
</pre>

Module2 : Helper

<pre>
define(function(require) {
      var Helper = Backbone.View.extend({
         initialize : function(options) {
            console.log('Inside Helper initialize');
         }
      });
});
</pre>

**Expected Result** : 
1. Application Starter needs to load from **//localhost:9000/assets/resources/modules/applicationstarter**.
2. Utility needs to load from
**//localhost:9000/assets/resources/modules/commons/utility**.
3. Boot Loader needs to load from
**//localhost:9001/assets/modules/bootloader**.
4. Helper needs to load from
**//localhost:9001/assets/modules/helper/helper**.

**Actual Results**
Point 1, 3 and 4 are working fine from the Expected Result. But Application1 tries load Utility module from **//localhost:9001/assets/modules/commons/utility** because its using baseUrl of Application2 from Application2 Requirejs configuration but I need that if Application1 tries to load its own modules  then baseUrl should be its own.

I tried to solve this problem using following solutions but it's not working
http://requirejs.org/docs/faq-advanced.html#rename

**Comment by LeoDutra** [comment]
Any change on this?

**Comment by Virbhadrasinh** [comment]
I tried two ways to solve this problems and both are working for me.
1. If applications are context independent then we can use [Multiversion Support](http://requirejs.org/docs/api.html#multiversion) for  resolve this problem.
2. Using r.js rename particular module and use that module in other application.
I will take the above example for explain second solution

In application 2 **Boot Loader** I required **Application Starter** which internally ask for  **'modules/commons/utility'**. So, I had made following changes to make it work,

1. Added **'modules/commons/utility'** and **'modules/applicationatarter'** in application 1 require config path
<pre>var require = {
        baseUrl : '/assets/resources',
        paths : {
              dateLib : 'libraries/dateLib/date',
              utility : 'modules/commons/utility',
              appStarters : 'modules/applicationstarters'
        }
}</pre>

2. Updated Application Starter
<pre>
define(function(require) {
      var Utility = require('utility');

      var ApplicationStarter = Backbone.View.extend({
         initialize : function(options) {
	        console.log('Inside ApplicationStarter initialize');
            new Utility(options); 
         }
      });
});
</pre>

3. r.js/build.js file's modules object
<pre>
 modules : [ {
                   name : "utility",
		   include : "utility",
		   exclude : ["jquery", "underscore", "backbone", "text", "less-builder", "normalize"]
		   }, {
		   name : "appStarters",
		   include : "appStarters",
		   exclude : ["jquery", "underscore", "backbone", "text", "less-builder", "normalize", "utility"]
        } ]
</pre>

4. Updated application 2 require config 
<pre>var require = {
        baseUrl : '/assets',
        paths : {
              jqueryui : 'libraries/jquery-ui/js/jquery-ui',
              utility : '//localhost:9000/assets/resources/modules/commons/utility',
              appStarters : '//localhost:9000/assets/resources/modules/applicationstarters'
        }
}</pre>

5. Updated application 2 Boot Loader
<pre>
define(function(require) {
      var Helper = require('modules/helper/helper');       
      var ApplicationStarter = require('appStarters');

      var BootLoader = Backbone.View.extend({
         initialize : function(options) {
	        console.log('Inside BootLoader initialize');
            new Helper(options); 
            new ApplicationStarter(options); 
         }
      });
});
</pre>

**We can write Node or Rhino script to generate r.js/build.js file**
