### ISSUE TITLE
Require JS fails with script error when web proxy refuses connection (does not allow for fallback to locally hosted script)

### ISSUE THREAD

**Issue by andersonk17474** [requirejs/requirejs#1123]
When the external internet connection is blocked by proxy, but local intranet server requests are functional, external CDN hosted javascript files in the requirejs paths cause requirejs to fail with script errors, even if local fallback files are listed in the path definition:

<main.js>
require.config({
    appDir: ".",
       baseUrl: "js",
paths: { 
        /\* Load jquery from google cdn. On fail, load local file. _/
        'jquery': ['//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min', 'vendor/jquery-1.11.0.min'],
        /_ Load jquery from google cdn. On fail, load local file. */
        'jstree': ['//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.0/jstree.min', 'vendor/jstree.min'],
        'nouislider' : 'vendor/jquery.nouislider.min',
        'underscore' : ['//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min', 'vendor/underscore-min'],
        'dygraph' : ['//cdnjs.cloudflare.com/ajax/libs/dygraph/1.0.1/dygraph-combined','vendor/dygraph-combined'],
        'moment' :  ['//cdnjs.cloudflare.com/ajax/libs/moment.js/2.6.0/moment.min','vendor/moment.min'],
        'datatables': ['//cdn.datatables.net/1.10.0/js/jquery.dataTables', 'vendor/jquery.dataTables'],
        'scrollTo' : 'vendor/jquery.scrollTo.min',
        'text' : 'vendor/text',
         'templates': '../templates',
    },

</main.js>

Error: Script error for: moment http://requirejs.org/docs/errors.html#scripterror

...{c=c[b]});return c}function C(b,c,d,g){c=Error(c+"\nhttp://requirejs.org/docs/er...

require.js (line 8)
Error: Script error for: dygraph http://requirejs.org/docs/errors.html#scripterror

...{c=c[b]});return c}function C(b,c,d,g){c=Error(c+"\nhttp://requirejs.org/docs/er...

require.js (line 8)
Error: Script error for: underscore http://requirejs.org/docs/errors.html#scripterror

...{c=c[b]});return c}function C(b,c,d,g){c=Error(c+"\nhttp://requirejs.org/docs/er...

require.js (line 8)
Error: Script error for: jstree http://requirejs.org/docs/errors.html#scripterror

...{c=c[b]});return c}function C(b,c,d,g){c=Error(c+"\nhttp://requirejs.org/docs/er...

require.js (line 8)

**Comment by mlarionov** [comment]
I have the same problem The web proxy returns HTML code and status 200. requirejs loads the file with error, but does not use a fallback even though it is specified. I am using version 2.1.10
