### ISSUE TITLE
jQuery plugin plugins

### ISSUE THREAD

**Issue by alex-phillips** [requirejs/requirejs#1142]
I'm trying to load in a jQuery plugin (FooTables) as well as its own plugins. I'm trying to steer clear of putting all of my paths / shims into the main.js file since our project is quite large and this plugin will not be used anywhere. Please let me know if I'm on the right track or a way I can achieve what I'm trying to.

What happens below when I run the code (not optimized) is that the FooTables will get initialized SOME of the time, but others, it will get to the `$('#footable-' + i).footable();` line and say 'undefined is not a function'.

Thanks in advance!

jQuery and 'config' are both previously defined in my main.js file

``` javascript
require([
    'config'
], function ($, config) {

    require.config({
        paths: {
            'FooTable-Main': 'vendor/plugins/footables/footable',
            'FooTable-Filter': 'vendor/plugins/footables/footable.filter',
            'FooTable-Sort': 'vendor/plugins/footables/footable.sort',
            'FooTable-Striping': 'vendor/plugins/footables/footable.striping'
        },
        shim: {
            'FooTable-Main': {
                deps: ['jquery']
            },
            'FooTable-Filter': {
                deps: ['jquery', 'FooTable-Main']
            },
            'FooTable-Sort': {
                deps: ['jquery', 'FooTable-Main']
            },
            'FooTable-Striping': {
                deps: ['jquery', 'FooTable-Main']
            },
        }
    });

    var plugins = [
        'jquery',
        'config',
        'FooTable-Main',
        'FooTable-Filter',
        'FooTable-Sort',
        'FooTable-Striping'
    ];

    require(plugins, function($, config){
        $(document).ready(function(){
            if (typeof config.footable !== 'undefined') {
                for (var i = 0; i < config.footable.num_tables; i++) {
                    $('#footable-' + i).removeAttr('hidden');
                    $('#footable-' + i).footable();
                }
            }
        })
    })

});
```

**Comment by tkaria** [comment]
@exonintrendo Did you ever manage to shim footable? I'm trying to do the same now and can't quite get it. Same error as you.

**Comment by exonintrendo** [comment]
@tkaria Here's what I ended up doing and it seems to be working. Pretty hacky, I'm sure there's a better way. But it works :-P. Let me know if you find anything better.

```javascript

require([
    'jquery'
], function ($) {

    var plugins = [
        'vendor/plugins/footables/footable',
        'vendor/plugins/footables/footable.filter',
        'vendor/plugins/footables/footable.sort',
        'vendor/plugins/footables/footable.striping'
    ];

    require([
        'jquery',
        'vendor/plugins/footables/footable'
    ],function(){
        require(plugins, function(){
            $('#my-footable').footable();
        })
    });

});
```

**Comment by tkaria** [comment]
Oh my. There must be something nicer. Thanks for sharing. Will let you know
what I find. Thanks.

Sent from my iPhone

On Apr 1, 2015, at 20:26, Alex Phillips <notifications@github.com> wrote:

@tkaria <https://github.com/tkaria> Here's what I ended up doing and it
seems to be working. Pretty hacky, I'm sure there's a better way. But it
works :-P. Let me know if you find anything better.

require([
    'jquery'
], function ($) {

    var plugins = [
        'vendor/plugins/footables/footable',
        'vendor/plugins/footables/footable.filter',
        'vendor/plugins/footables/footable.sort',
        'vendor/plugins/footables/footable.striping'
    ];

    require([
        'jquery',
        'vendor/plugins/footables/footable'
    ],function(){
        require(plugins, function(){
            $('#my-footable').footable();
        })
    });

});

—
Reply to this email directly or view it on GitHub
<https://github.com/jrburke/requirejs/issues/1142#issuecomment-88584985>.
