### ISSUE TITLE
Shim dependency variable names

### ISSUE THREAD

**Issue by Ciantic** [requirejs/requirejs#1160]
**Currently**

Consider I have a shim:

```
shim : {
    'myapp': {
        deps: ['jquery', 'underscore', 'backbone'],
        exports: 'Application'
    }
}
```

The myapp _requires that the Backbone variable is defined_, the above shim can't work. Because Backbone for one, is not defined using current shim compilation. Require JS (r.js compiler) compiles the above shim to file with:

```
// jquery file
// underscore file
// backbone file
// myapp file
define("myapp", ["jquery","underscore","backbone"], (function (global) {
    return function () {
        var ret, fn;
        return ret || global.Application;
    };
}(this)));
```

Of course it can't work, the myapp file should be _inside the generated define_. 

**Suggestion to fix this**

In order to do that requirejs should have extra shim argument e.g. `depnames`:

```
shim : {
    'myapp': {
        deps: ['jquery', 'underscore', 'backbone'],
        depnames: ['$', '_', 'Backbone'],
        exports: 'Application',
    }
}
```

Which would compile to correct:

```
// jquery file
// underscore file
// backbone file
define("myapp", ["jquery","underscore","backbone"], function ($, _, Backbone) {
    // myapp file
    return Application;
});
```

Voi'la!

**Comment by pmstss** [comment]
sorry for a bit offtopic, but it's first google result for "var ret, fn; return ret". i see these lines in many project, but don't understand the sense. could anybody please explain it for the requirejs newbee?
function () {
  var ret, fn;
  return ret || global.Application;
}
where it come from? why not just return global.Application?

**Comment by jrburke** [comment]
@pmstss if an "init" property is part of the shim config, then that function will have extra code for calling init, and ret will be the return value for that function. However, if no "init" section, then that is the code result from the r.js optimizer.
