### ISSUE TITLE
Remove data-main support for config?

### ISSUE THREAD

**Issue by conficient** [requirejs/requirejs#1182]
The data-main attribute feature allows the require.config (also known as main) script to be loaded and executed asynchronously. This means that any calls to require **cannot depend on the settings in the config being loaded**. This leads to unpredictable results in the browser - sometimes it's loaded, sometimes it's not, when you call require().

I have just wasted two days trying to figure out why my config settings were ignored because of this 'feature'. This makes me think this is a tool for helping newbies like me shoot themselves in the foot at the outset, just because they followed most of the examples out there, because that's what they all suggest. Not a good way to encourage uptake.

**Comment by cention-mujibur-rahman** [comment]
@jrburke I am having a problem when using this way:
<addr><script async src="app/main.min" src="/vendor/requirejs/require.js" ></script></addr>
for slow connection(I tested it in chrome: GPRS 50kb/s 20 kb/s 500ms) except throttle connection, I got this error
`main.min.js(it is optimized by r.js)` has been included the requirejs configs
<addr>
require.js?v=20170215:165 Uncaught Error: Load timeout for modules: main.min
http://requirejs.org/docs/errors.html#timeout
</addr>
But when using separate script tag to load require.js and main.min.js then it works. like that
<addr><script src="/vendor/requirejs/require.js"></script></addr>
<addr><script async src="/app/main.min.js" ></script></addr>
Is it sound okay?

**Comment by jrburke** [comment]
That should be fine, but you can also update the load timeout interval via [waitSeconds](http://requirejs.org/docs/api.html#config-waitSeconds) config. Set the config first then try loading the main script:

```html
<script src="/vendor/requirejs/require.js" ></script>
<script>
requirejs.config({ waitSeconds: 120, baseUrl: 'app' }); 
requirejs(['main.min']);
</script>
```
