### ISSUE TITLE
Using requirejs inside a file in paths uses unexpected base url.

### ISSUE THREAD

**Issue by ryasmi** [requirejs/requirejs#1217]
**RequireJS version**
2.1.10

**Steps to reproduce**
- Create a index.html file containing with requirejs included and the data-main attribute set to `app/config.js`.
- Make a `app/config.js` file similar to this...

``` js
requirejs.config({
  paths: {
    commons: '../commons/main'
  }
});

require(['commons'], function(commons) {
  console.log(commons);
});
```
- Make a `commons/main.js` file like this...

``` js
define([
  './first',
  './second'
], function(first, second) {
  return {
    first: first,
    second: second
  };
});
```
- Make a `commons/first.js` file like this...

``` js
define([], 'first');
```
- Make a `commons/second.js` file like this..
  .

``` js
define([], 'second');
```

_This is obviously a very useless example but it demonstrates the issue I'm having._

**Expected behaviour**
I expect `./first` to be required in `commons/main.js` from `commons/first.js` because otherwise it seems to me that I have to either (a) put all my code from `commons/first.js` and `commons/second.js` into `commons/main.js`, or (b) use the r.js optimiser. Ideally I don't want to use either of those as there could be a situation where I just want `first` in some parts of my project.

**Actual behaviour**
Requiring `./first` in `commons/main.js` actually goes to `app/first.js` which does not exist.

**Additional information**
I'm not sure if this is the best way to do things but it definitely makes sense to me.

To be clear, my file structure in my "Steps to reproduce" is this...
- app/
  - config.js
- commons/
  - main.js
  - first.js
  - second.js
- index.html

**Comment by ryansmith94** [comment]
@jrburke thanks for that, that makes sense :D
