### ISSUE TITLE
Config urlArgs not working when apps developed as cordova application in Windows Phone

### ISSUE THREAD

**Issue by niwasmala** [requirejs/requirejs#1459]
Greetings, I'm currently developing a hybrid application using Cordova with RequireJS. It's all worked fine as expected on Android, iOS, BB 10, but when we try to port to Windows Phone, I found something strange. 

Here is the simple code, not the actual code, but perhaps can be used to debug.

index.html
```html
<html>
<body>
   <script type="text/javascript" src="require.js"></script>
   <script type="text/javascript" src="test1.js"></script>
   <script>
      requirejs.config({
         urlArgs: "_v=1"
      });
   </script>
</body>
</html>
```

test1.js
```javascript
requirejs([
  "test2"
], function(test2){
   console.log(typeof test2);
   console.log("test1.js");
});
```

test2.js
```javascript
define([], function(){
   console.log("test2.js");
   return {
      "simple": "object"
   };
});
```

As you can see, when load test1.js, it should load test2.js first, and run function inside and return the value, so the expected result should be something like this.

Expected Result
```console
test2.js
object
test1.js
```

But, the log says different, it load test1 first then load test.

Actual Result
```console
undefined
test1.js
test2.js
```

After many try and error, when I remove urlArgs from requirejs.config, it works!
I don't know why but I hope anyone who find similar problem find this useful.

**Comment by jrburke** [comment]
Thanks for sharing this. I do not have an environment where I can look into the behavior, but also expect it to be a niche error. Closing as a discussion/fyi issue, feel free to continue discussion here.
