### ISSUE TITLE
Cannot pass array to wrap.startFile config via command line

### ISSUE THREAD

**Issue by javasplice** [requirejs/requirejs#1463]
I am calling _r.js_ through _node_ in the command line. Some optimizer configuration options must be provided as arguments through the node call because the directory in which the files exist is dynamic. One of the configuration options I am attempting to pass is "wrap.startFile" because I want to inject a couple file at the top of the build output.

The command line call looks something like this:
```
node r.js -o path/to/r-config.js ... wrap.startFile=path/to/file1.js,path/to/file2.js
```

When the build is executed, I receive an error message similar to the folllowing:
```
Error: Error: Malformed wrap config: Error: ENOENT, no such file or directory 'path/to/file1.js,path/to/file2.js'
    at normalizeWrapConfig (.../r.js:29397:19)
```

It appeared as though the argument was being passed as a string instead of being parsed into an array. I investigated the problem and tracked it back to `build.convertArrayToObject`. This function has a variable called `needArray` that lists the configuration values that should be parsed into arrays. Anything to do with "wrap" was conspicuously absent. I added `"wrap.startFile": true` to the map and the optimizer then properly parsed the argument into an array.

Although that fixed the "wrap.startFile" problem, there are a number of configuration options that can be arrays that are not being parsed at the moment. One solution would simply be to add them all to the `needArray` variable, but that would be messy and brittle.

**Comment by javasplice** [comment]
To clarify, I was using version 2.1.20 for this, but I tested the latest version (2.1.22) and the issue was the same.

**Comment by Botnary** [comment]
why don't you put this in your r-config.js ?
````  
 wrap: {
        startFile: ["parts/startOne.frag", "parts/startTwo.frag"],
        endFile: ["parts/endOne.frag", "parts/endTwo.frag"]
 },
```
Also have you read the docs on `r.js` ? http://requirejs.org/docs/optimization.html#basics
it says `You can either specify options on the command line OR a build profile`, but i see there that you are combining command line options with a build profile :)

**Comment by javasplice** [comment]
As I stated in the original post, the wrap configurations must be specified as command line arguments because the directory in which the files exist is dynamic. To be more explicit, different files need to be included for debug and release builds. I am attempting to avoid having two separate configuration files by passing in the dynamic properties through the node call.

And yes, I have read the documentation. I'm not exactly sure what you are trying to imply, but it seems that you are saying that the "OR" in that sentence is exclusive, that you can only specify options in the command line _OR_ in a build profile. This is false; if you keep reading, the documentation states that `Command line arguments take precedence over build profile settings, and you can mix them together`. So this is clearly functionality that should be supported.

And to be clear, I am not asking for assistance alternative solutions; I am pointing out a bug.

**Comment by jrburke** [comment]
The work for this would be done in [build.convertArrayToObject](https://github.com/jrburke/r.js/blob/5cd88c87839b3c2e72d872a90436f0270d611fd0/build/jslib/build.js#L774). Right now it just does work on non-nested values, but I can see expanding it to support converting `wrap.startFile=...` to `wrap: { startFile: ...}`
