### ISSUE TITLE
Add skipArrays option for when using mainConfigFile

### ISSUE THREAD

**Issue by DominicTobias** [requirejs/requirejs#1480]
Hi, I noticed that merging can be handy but also very limiting when using `mainConfigFile`. For example a config `deps` might look like:

```js
deps: ['mocks', 'main']
```

When building I don't want to include all the mocks:

```js
name: '../bower_components/requirejs/require',
mainConfigFile: './require.config.js',
deps: ['main']
```

It would be great if that was possible but because there isn't a way to specify `skipArrays` value to `mixConfig` I have had to make a workaround, which only works since I only have 1 build dep:

```js
paths: {
  requireLib: '../bower_components/requirejs/require'
},
include: ['requireLib'],
deps: null,
name: 'main' // Use name as entry point
```

**Comment by jrburke** [comment]
I can see this as not being as elegant, but it is not clear to me how to make it nicer without causing some backwards compat issues around the expectations of merged values. What you have is probably the best way to go about it, that or using the include: [] array with the `deps: null`.

Closing as a discussion ticket, feel free to continue discussion here.
