### ISSUE TITLE
nested requires don't load on first page load

### ISSUE THREAD

**Issue by YonatanKra** [requirejs/requirejs#1482]
I think I have something similar to #1457 and might be connected to  #173.
Here's my a sample code:

`main.js`:
```
require.config({
  paths: {
    app: '../js/app',
    modulesPath: '../js/modules',
    moduleOne: 'modulesPath/moduleOne/index'
  },
  deps: ['app']
});
```

`app.js`:
define(['moduleOne'], function(){
});

`moduleOne/index.js`:
```
define(['modulesPath/moduleOne/moduleOne`], function(){
  require(['modulesPath/moduleOne/someModule/someModule']);
  require(['modulesPath/moduleOne/someOtherModule/someOtherModule']);
  require(['modulesPath/moduleOne/someDifferentModule/someDifferentModule'], function(){
    require(['modulesPath/moduleOne/someDifferentModule/subFolder/moduleHelperFile']);
  });
});
```

The issue is:
`moduleHelperFile` doesn't seem to load on first page load. It does load when I refresh the page.  This is quite consistent.
Any idea why?

**Comment by jrburke** [comment]
It is hard to know the exact problem without a test case to try. It is expected to work though. 

Going to close for now, but if you have a test cast that can be tried, leave the info here and we can reopen as needed.
