### ISSUE TITLE
takeGlobalQueue() and anonymous modules

### ISSUE THREAD

**Issue by z-vr** [requirejs/requirejs#1493]
Hola! A great js-cookie module [has](https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L10) the following code:
```js
if (typeof define === 'function' && define.amd) {
	define(factory);
}
```
Therefore, when it is added to the page not with requirejs, the module [will be pushed](https://github.com/jrburke/requirejs/blob/master/require.js#L2112) to the `globalDefQueue` when _define_ is called: `globalDefQueue.push([name, deps, callback]);`, with name equal to null and deps equal to []. However, the `intakeDefines` method with then [check](https://github.com/jrburke/requirejs/blob/master/require.js#L1254) for the name of the module and raise an error when name is null:
```
takeGlobalQueue();
//Make sure any remaining defQueue items get properly 
while (defQueue.length) {
    args = defQueue.shift();
    if (args[0] === null) {
        return onError(makeError('mismatch', 'Mismatched anonymous define() module: ' +
        args[args.length - 1]));
    } 
}
```
is that expected behaviour? Why is _define_ function ok with pushing an anonymous method to the `globalDefQueue`, but _intakeDefines_ is not ok with reading the anonymous method?

**Comment by jrburke** [comment]
It sounds like js-cookie was loaded by a script tag and not via a requirejs() or define() call. In this case, requirejs has no idea what module ID to give to the module in that case and it results in this error.

Fixes are:

* load the script with requirejs
* Place the script tag for js-cookie before the require.js script tag if you do not want requirejs to see the script.

Closing as a discussion ticket, feel free to continue discussion here.
