### ISSUE TITLE
localrequire in plugin

### ISSUE THREAD

**Issue by aleclofabbro** [requirejs/requirejs#1494]
I wrote a plugin which loads a custom text.
the plugin's load method has the documented `localrequire` argument and it is able to load the correct  resource(relative to caller) by mean of `localrequire.toUrl`.
The custom text defines, in some way, other custom text resources that must be loaded, and those definition are relative to the resource itself.
How can i obtain a localrequire relative to the loaded resource so to recursively load sub referenced resources, keeping the global require config?
I tried to make a new `require` by mean of `require.config(ctx_config)` having `ctx_config` as a shallow copy of `require.s.contexts._.config`, overriding the baseUrl properly, and setting a context property..
relative paths load ok, but other paths, and those copied from global require's config becomes relative to the new context, breaking expected resolution.

**Comment by aleclofabbro** [comment]
To be a bit clearer:
I'd like to obtain the corresponding of `"require"` dependance in a js file 
```
define(['require'],function(localrequire){ 
// localrequire is  relative to this module
}) 
```
but relative to another resource type, retrieved by my custom plugin:
```
define(['./xhr'], function(xhr) {
  var _module = {
    load: load
  };
  return _module;

  function load(name, localrequire, onload, config) {
   var resource_url = localrequire.toUrl(name);
    xhr.get(resource_url, function(text){
        var other_deps = get_sub_dependencies(text);
        // here i wish to require deps relative to the loaded text
        _desired_localrequire_relative_to_resource_url(other_deps, function(/* deps */){
            onload(/*whatever*/);
        });
    });
  }
```

**Comment by aleclofabbro** [comment]
i'll write down a use case with json instead of text:
folder structure
```
root/
    main.js
    plugin.js
    baseurl/
        confs/
            conf.json
            subpath/
                module0.js
        path1/
            module1.js
        path2/
            module2.js            
```
root/confs/conf.json:
```json
[
    "./subpath/module0",
    "path1/module1",
    "path-two/module2"
]
```
plugin.js:
```js
define(['xhr-get'],function(xhrget){
    return {
        load:function(name, localrequire, onload, config){
            var url = localrequire.toUrl(name);
            xhrget(url,function(json){
               //here i need a localrequire relative to the loaded json..
               sub_localrequire(json,function(/*modules*/){
                   var results = Array.prototype.slice.call(arguments);
                   onload(results);
               });
                var result = json.
            })
        }
    }
})
```
main,js:
```js
require.config({
    baseUrl:'baseurl',
    paths:{
        'path-two':'path2'
    }
});
require(['plugin!confs/conf.json'],function(results){
   // here i should have:
   // results[0]  = module0
   // results[1]  = module1
   // results[2]  = module2
});
```

**Comment by jrburke** [comment]
It is not possible to get the relative require for the strings in conf.json. What you could do is use load.fromText and define a module that has those strings as dependencies, and that should work.

```javascript
define(['xhr-get'],function(xhrget){
    return {
        load:function(name, localrequire, onload, config){
            var url = localrequire.toUrl(name);
            xhrget(url,function(json){
                onload.fromText('define(' + JSON.stringify(json) + ', function() {});');
            })
        }
    }
})
```

Closing as a discussion ticket, feel free to continue discussion here.
