### ISSUE TITLE
More complete contextual require API for better unit-testing

### ISSUE THREAD

**Issue by dcleao** [requirejs/requirejs#1495]
There are several challenges in being able to properly unit-test RequireJS modules.

1. RequireJS contexts are not disposable/destroyable and this causes memory-leaks (existing, old issue https://github.com/jrburke/requirejs/issues/1113)
2. RequireJS contexts start out with an empty configuration, but in tests, typically, the configuration of the default context is/would be desired
3. RequireJS contexts don't have a method for defining a module directly in them, for mocking purposes, for example; `define` calls place definitions in the "global defs queue" and the first following `require` call takes these as its own. So to use the global `define` function to define modules in a context, one has to be sure to immediately call the context's require function to avoid those definitions being captured by some other context. This behavior/limitation can easily lead to hard to detect bugs.

Existing RequireJS testing-frameworks (e.g. Squire, Jasq) vary in how they attack these problems. All use undocumented APIs to get the job done. Also, unfortunately, they also mix the complementing of RequireJS functionality with the integration with the testing framework (e.g. Jasmine).

I tried to create the code I would like to see exposed **and maintained directly by** RequireJS — keeping it independent of any testing environment, its features to a minimum, and as close as possible to RequireJS's API spirit. This could be distributed as a separate extension to RequireJS (like the linked proposal proves) or be integrated in the core file.

Over this extended API, RequireJS testing libraries would perform the integration with testing frameworks, providing varying capabilities and their taste of API.

Proposal: https://github.com/dcleao/pentaho-platform-plugin-common-ui/blob/test-requirejs/test-js/unit/require-test.js

Example usage:
```js
var localRequire = require.new()
        .define("my/foo", {
          act: function() { return "mocked-value"; }
        })
        .config({
          config: {
            "my/bar": {mode: "fast"}
          }
        });

localRequire(["my/bar"], function(bar) {
   // test `bar`, that depends on "my/foo"
   
   // dispose context
   localRequire.dispose();
});
```

What do you think?

**Comment by dcleao** [comment]
Hi, does this make any sense?

**Comment by jrburke** [comment]
I could see a case for localRequire.define(), and perhaps a .dispose(), but I am very sensitive the size of requirejs, and do not want to add more code size for a case that is really just needed for test scenarios.

If you wanted some helpers for the test case though, I think something like this might be enough:

```javascript
// Creates a context-specific define
function contextDefine(contextName) {
  var context = requirejs.s.contexts[contextName];
  return function() {
    var args = slice.call(arguments),
        id = args[0];
    context.defQueueMap[id] = true;
    context.defQueue.push(args);
  }
}

// Assuming 'test' context is already set up:
var testDefine = contextDefine('test');
testDefine('my/foo', function() {});

// To delete a context and its data.
function contextDelete(contextName) {
  delete requirejs.s.contexts[contextName];
}
```
I think the value in requirejs at this point is its stability with just small fixes. Larger API changes really need a bigger version rev, but then I would also want to modernize the internals at the point, along the lines of [alameda](https://github.com/requirejs/alameda).

So closing for now, with the helpers above probably enough for test scenarios.

**Comment by dcleao** [comment]
While these snippets handle concerns 1) and 3) above, we're still in need to 2) clone an existing configuration, possibly achieved through multiple `require.config` call and 4) not having to maintain code that accesses internals of requirejs.

I understand your concern over file size and stability, but if this feature set were provided as a pair/extension file, that wouldn't be a problem.

By what I understand, alameda is _fully_ compatible with both requirejs and r.js, with the following differences:
1. Has a new `defaultErrback` — no problem, helps with backward compatibility
2. `require.undef()` is not defined — not a problem, if the proposed disposable contexts would exist
3. `onResourceLoadNestedRequire` — don't know what this is needed for

It also depends on an ES5-compatible browser. So it is looks like a natural upgrade path, as soon as the browser requirements are met.

However, alameda also does not seem to solve any of the items I am asking for.

Ease of testability is a fundamental requirement for any moderate size AMD application, whether it uses requirejs or alameda, and it would be great that you could provide the core functionality that supports this.

You could design it "well" for alameda, possibly including the functionality in the main file, and then, for requirejs, have an API compatible, possibly hacky, "server-side" version or companion test file. For us, it would work equally for alameda or requirejs, as is currently the case for the remaining functionality.

If, for example, I'd use Squire.js now, it would not work for alameda later, out of the box, who knows if ever (unless the private details are identical, haven't looked to the alameda code in detail).

In anyway, thank you for the time you took to look at this.
