### ISSUE TITLE
require.js timeout issue on slow networks when optimized using r.js...

### ISSUE THREAD

**Issue by jdspecht** [requirejs/requirejs#1496]
Hi -

require.js will throw a timeout error when loading my optimized main.js file because I set the waitSeconds value to 0 in main.js itself...so it will never get set before the default 7 second timeout.

May I suggest a simple enhancement to set the timeout on the require js script tag itself, something like:

`<script data-main="scripts/main.js" data-wait-seconds="0" src="scripts/require.js"></script>`

That way, a waitSeconds value can be set immediately when require is loaded so that it can be applied on the first "require" of the data-main script. This would help tremendously and would help me (and likely many others with the same issue) to avoid applying hacky solutions.

**Comment by jrburke** [comment]
The library supports multiple calls to requirejs.config(), and if `requirejs` is an object before require.js is loaded, then requirejs treats that as a requirejs.config() call. So this should fix the problem for this case:

```html
<script>var requirejs = { waitSeconds: 0 };</script>
<script data-main="scripts/main.js" src="scripts/require.js"></script>
```

No plans to support more data- args in the interest of keeping the file size of the lib down.
