### ISSUE TITLE
Shim for patching modules

### ISSUE THREAD

**Issue by myxibrium** [requirejs/requirejs#1500]
We have a shim for loading a module BEFORE another module (as a dependency), but not for loading AFTER (like a patch or plugin). This has some valid use-cases, especially for things like jQuery. See this StackOverflow: http://stackoverflow.com/questions/18362930/load-modules-automatically-via-requirejs

I would like to request this feature because I think it would be very useful, and it's essentially a short-hand for making a new module which requires some modules and returns the "main" module, so it should be possible and easy to implement.

Thanks

**Comment by jrburke** [comment]
[map config](http://requirejs.org/docs/api.html#config-map) can be used to point to some other module that first loads the base module, then does modifications and returns a module that will then be used by other modules, according to the map configuration.

So I believe that should be enough to get the described behavior. Closing as a discussion ticket, feel free to continue discussion here.
