### ISSUE TITLE
AMD Factory function incorrectly needs return statement

### ISSUE THREAD

**Issue by branneman** [requirejs/requirejs#1503]
Given:
- The AMD spec states that the value of "require", "exports", or "module" should be as defined by the CommonJS modules spec [[source](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#dependencies-)]
- The AMD spec states it is optional to return a value from the factory function [[source](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#factory-)]
- The CommonJS modules spec states that modules must use the "exports" object as the only means of exporting [[source](http://wiki.commonjs.org/wiki/Modules/1.1#Module_Context)]
- Both code snippets below are correct AMD

The bug:
**Require.js expects the factory function to return, which is not correct according to both specs.**

Snippet 1: Does not work with Require.js:
```js
define(['exports'], function(exports) {
    function MyModule() {}
    exports = MyModule;
});
```

Snippet 2: Does work with Require.js:
```js
define(['exports'], function(exports) {
    function MyModule() {}
    return exports = MyModule;
});
```

**Comment by jrburke** [comment]
What is supported is what node supports:

```javascript
define(['module'], function(module) {
    function MyModule() {}
    module.exports = MyModule;
});
```

So, while not strictly CommonJS, node is not either, but it seemed better to conform to the dominate commonjs-ish platform, node. `module.exports = ` is also very idiomatic for node, so the interior of the AMD factory function is more likely to be translatable to that environment, and vice versa.

Closing as a discussion ticket, but feel free to continue discussion here.
