### ISSUE TITLE
Allow the name of the sourcemap to be set as part of config

### ISSUE THREAD

**Issue by marcoscaceres** [requirejs/requirejs#1507]
We have specific release versions of a generated file and accompanying map file (e.g., foo-v1.js). Right now, by default, setting the `generateSourceMaps` options in the config automatically names the source map using the name property (I guess). It would be useful to be able to configure what the name of the source map will be. 

So, something like:
```JS
version = "1.2.3"; 
{
sourceMapName: `foo-${version}.build.map`
}
```

**Comment by jrburke** [comment]
The source map generation pipeline is probably one of the most fragile pieces, and I prefer not to mess with it. So no plans to support this. Some possible alternatives:

1) Create a post r.js build step which just renames the file and updates the sourceURL comment in the JS file.

2) If you want very granular control over bundle making, what minifier to use, and how to chain sourcemap generation, [amodro-trace](https://github.com/amodrojs/amodro-trace) gives a very basic JS API to trace modules, allowing a very custom build processes.

**Comment by marcoscaceres** [comment]
@jrburke, thanks for your consideration. I  did [option 1](https://github.com/w3c/respec/pull/614/files#diff-6bf107120d26767e3bf633c7a40433c9R18) (linking in case others are interested in seeing it).
