### ISSUE TITLE
Include RequireJS module declared in html <script> tags in build

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/requirejs#1512]
I have this RequireJS module declared in a script tag block in my index.html file like so:

```html
<script>

    define('@AdminUIConfig', [], function () {
        return new Object(<%- data %>);
    });

</script>
```

this is of course to populate a RequireJS module with config data from the server using EJS templating

this was working in development but when I tried to run a production build with r.js I get this:

```bash
[18:06:19] 'optimize' errored after 1.76 s
[18:06:19] Error: Error: ENOENT: no such file or directory, open '/Users/amills001c/WebstormProjects/baymax/AdminUI/public/static/@AdminUIConfig.js'
In module tree:
```

now, it makes sense that it can't find the "file" because it's not referenced in my requirejs.config({}).
So my question is, is this pattern (declaring a module like this in html) an OK one, and if so, how can I prevent the build from breaking with its existence? Perhaps I can _ignore_ it somehow?

**Comment by jrburke** [comment]
Sounds like you can set the build config paths info to use 'empty:' as the value to get the build to work, more info about 'empty:' here:
http://requirejs.org/docs/optimization.html#empty

Closing as a discussion ticket, feel free to continue discussion here.
