### ISSUE TITLE
R.js compilation breaks javascript

### ISSUE THREAD

**Issue by miraclebg** [requirejs/requirejs#1514]
Hello!

I am having a really irritating issue on which i've already lost 20+ hours...

For whatever reason r.js is breaking up the syntax of the final built javascript like this:

"SyntaxError: Unexpected string literal ")". Expected ')' to end a argument list."

It's really difficult to trace down what is causing it but i've been able to i think find it by stripping down the code file by file, file section by section....

It seems the word "href=
[bootstrap.js.zip](https://github.com/requirejs/requirejs/files/183736/bootstrap.js.zip)
" or where it is contained is causing this.

For example right now i have reached down to bootstrap sources and when i remove the two lines in the file which refer to this - the compilation is suddenly ok...

Or - if i just rename 'href' to 'href1' - it's also fine.

I've attached the file and added a comment above the problematic places: // HREF ISSUE - it's very easy to replicate this - add this an amd dependency, use it in a module and try to compile it. As soon as you rename 'href=' to 'href1=' it goes away.

The build configuration file..really does not matter.. i've tried everything - disabling optimization, changing the type.. nothing helps. Anyway i am attaching the config file for the build too.
[build.js.zip](https://github.com/requirejs/requirejs/files/183738/build.js.zip)

What can we do to solve this?

Thank you!

**Comment by miraclebg** [comment]
Here is what i see when this is loaded in the runtime... the debugger is somehow mistaking a part of jquery to have this issue..while this is really not the case (i think).
![screen shot 2016-03-22 at 10 34 04](https://cloud.githubusercontent.com/assets/126405/13945908/b867d6ae-f019-11e5-987c-f98bbc86f967.png)

**Comment by jrburke** [comment]
There doesn't seem to be enough to go on to diagnose the problem. Likely a running test of the failure would be able to provide more detail, but it is not clear yet what is the factor. Knowing the version of requirejs helps, but will not be enough to diagnose the problem.

Closing for now as there is not enough detail to diagnose the problem. However, feel free to continue discussion here, even adding a small test case, and we can reopen as needed.
