### ISSUE TITLE
Pattern for mirroring dependencies in a controller and a view

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/requirejs#1519]
This will be a little abstract. I have a SPA, and there is a front-end router.  The SPA is optimized so that the front-end will only fetch for a collection when that collection is needed by the next view. 

so my view might be:

```js
define(['COLLECTIONS/a',], function(collA){
   ///etc
});

```
and in the router/controller, we might have

```js
        upload: function () {
                var routerOpts = {
                 collectionsToFetch: ['COLLECTIONS/a']
                };
                this.changeView(routerOpts, function (cb) {
                    require([ 'REACT_VIEWS_BASE/SomeView'], function (UploadView) {
                        routerOpts.view = UploadView;
                        cb(null);
                    }, function errback(err) {
                        console.error(err);
                        cb();
                    });
                });
            },

```

what I am wondering is, in the spirit of DRY, if there is some way to share the information about the dependencies in a particular view (which collection it needs) and the dependencies listed manually in the router, in this case 

 ```js
       var routerOpts =  {
           collectionsToFetch: ['COLLECTIONS/a']
        };
```

now this might not be super useful because it's quite possible that the view itself doesn't need to reference the collection in the dependency array simply because it doesn't need that collection directly, only indirectly. Just wondering if you understanding what I am asking about and if there is a pattern for this thanks!

**Comment by jrburke** [comment]
The module system is geared towards explicit dependencies. For indirect things, the solution really depends on the app, but also means some of the more base modules may not be reusable across apps.

The only thing that comes to mind is using map config to point modules IDs to adapters that also load other modules. An example using jquery and a jquery-adapter as an example:
http://jrburke.com/talks/moduleids/#/13

Closing as a discussion ticket, but feel free to continue discussion here.
