### ISSUE TITLE
requirejs occurs error 'define is not a function'  when refreshing page after using r.js optimizes 

### ISSUE THREAD

**Issue by aoqier** [requirejs/requirejs#1522]
Hello, I use r.js to optimize the multi-page example downloaded from official website. But when i refreshing page occurs error that is 'define in not a function'.Is there someone run into this problem?

**Comment by aoqier** [comment]
I fount that sometimes define is null when the script which is added is data-main is loaded

**Comment by jrburke** [comment]
It sounds like the require.js file is not loaded via a script tag? I just tried https://github.com/requirejs/example-multipage and ran the `node tools/r.js -o tools/build.js` and it works for me.

If that same setup is occasionally failing for you, it would be good to know which browser you are using and if you are testing on a local server, what kind of server. If using a browser with add-ons or extensions in them, it might be good to turn them off to see if that is affecting it. I think I have had reports in the past that some very specific chrome extensions may interfere with script loading.

**Comment by aoqier** [comment]
Hey @jrburke  Thank you. I use gulp-server-livereload to start server and problem still happens.I use macos system, chrome browser, actually firefox in macos has that problem.

    page1.js:1 Uncaught TypeError: define is not a function

**Comment by jrburke** [comment]
I wonder if trying just loading the file via the built in web server on osx, or via a file:/// URL, without going through that server, if it works better. Firefox on macos is working for me via those two URL approaches.

**Comment by aoqier** [comment]
Wow, Thank you so much @jrburke . It solved. When i start server via nginx it works well.But i don't know  what the matter with gulp-server-livereload. hoho.

**Comment by jrburke** [comment]
Glad the root problem was found. Since this seems to be server tool related, closing out the issue.

**Comment by mkavrukova** [comment]
@jrburke: Did you ever found out what was wrong with gulp-server-livereload. I have the same problem and serving it with nginx will not be the solution for a dev set up in my case,
