### ISSUE TITLE
RequireJS: Multi Configuration - Multi-Application 

### ISSUE THREAD

**Issue by FlorianGrimm** [requirejs/requirejs#1524]
If I want to add an application on an existing web application (SharePoint) that already use RequireJS - can I provide another config for my application?
To prefix my modules wouldn't help for global settings.

Passing the config around, or something like that...

**Comment by jrburke** [comment]
It is possible to call requirejs.config() more than once. It will merge the config calls, last one wins over previous ones. So depending on the setup, that may be enough.

Closing as a discussion ticket, but feel free to continue discussion here.
