### ISSUE TITLE
In html5 worker, text plugin template load with .js

### ISSUE THREAD

**Issue by guodong** [requirejs/requirejs#1525]
In web worker, with the code:
```
define(['text!tpl/window.html', ....
```
the importScripts url is http://domain/tpl/window.html.js, but I need http://domain/tpl/window.html

**Comment by guodong** [comment]
I know importScripts must load valid js file, so is there any way to work with html template in web worker?

**Comment by jrburke** [comment]
Sounds like the text plugin thinks the request is a cross domain request, and it defaults to avoiding and XHR in that case. You can set a useXhr config for the text plugin to force xhr in that case, details here:
https://github.com/requirejs/text#xhr-restrictions

**Comment by guodong** [comment]
thx, @jrburke
