### ISSUE TITLE
requirejs not working with cordova on windows phone

### ISSUE THREAD

**Issue by flashmandv** [requirejs/requirejs#1527]
I have cordova app which uses requirejs to load modules.
The app works on android and iOS, but it doesn't work on windows phone.
The error is:

> Unhandled exception at line 8, column 137 in ms-appx-web://net.boardgamesonline.drawit/www/js/libs/require.js 0x800a139e - JavaScript runtime error: Load timeout for modules: sounds,libs/signals.min,config,components/share....

Here is the full info for the problem:
http://stackoverflow.com/questions/36570175/vs-cordova-wp8-requirejs-load-timeout-for-modules

**Comment by jrburke** [comment]
You can try setting [waitSeconds](http://requirejs.org/docs/api.html#config-waitSeconds) to 0, if it is just a matter of a slower phone that takes a while to load the resources. If that just prevents the error from being logged but the app is still broken, then it likely is a path problem.

You could try putting in alert statements at the top of the scripts that are loaded by the loader, just to see if the scripts are actually found and loaded correctly. If the alerts do not come up then that would indicate there is something weird with the path.

This issue about "text!..." resources might have some clues too:
https://github.com/requirejs/text/issues/54

but that is the extent of what I recall for windows phone.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by flashmandv** [comment]
The problem was resolved by creating fresh project in visual studio
