### ISSUE TITLE
can't use DOMContentloaded event

### ISSUE THREAD

**Issue by compasss** [requirejs/requirejs#1530]
I can't use DOMContentLoaded event in require modules.

codes:

define(['juqery', '_'], function($,_){
    document.addEventListener('DOMContentLoaded', functioin(ev){
        console.log(ev);
    })
})

**Comment by jrburke** [comment]
Modules can finish loading after that event. You will want to also check document.readyState to see if the document is already past that event. More details are in the [internals of the domReady loader plugin](https://github.com/requirejs/domReady/blob/7d6cafc360d611fdc3e03313fba2e7a508f9ce3d/domReady.js#L80).

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by compasss** [comment]
these code sometimes print 'loading' in console when browser network conditions transform to GPRS moduls;
list.js:
<pre><code>
define([ 'jquery', 'easyui'],function(){
    console.log(document.readyState);
})
</code></pre>

config.js:
<pre><code>require.config({
    paths: {
        'jquery': [
            path+'/js/jquery-1.7.2.min'
        ],
        'easyui':[
                  path+'/js/jquery.easyui.min'
        ],
        'list':[
            path+'/frame/shaicha/list/list_common'
        ]
    },
    shim: {
		'easyui': {
  　　　　　　　　deps: ['jquery']
		}
  　　}
});
require(['jquery','easyui','list'],function($,easyui,list){
	console.log(document.readyState);
	    listcommon.hander();
});
</code></pre>

**Comment by jrburke** [comment]
Correct, if the document.readyState is not in the right state, you still need to listen for the DOMContentLoaded event, and as an absolute fallback, the window load event.
