### ISSUE TITLE
`shim` and `packages` cannot work together?

### ISSUE THREAD

**Issue by nenadvicentic** [requirejs/requirejs#1532]
Is there a way to configure dependency of `CommonJS` type of package using `require.config`?

When we use `packages` configuration _(bootstrap is structured as a `CommonJS` package)_ , `shim` dependency is not respected:

```
require.config({
    shim: {
        "bootstrap": { deps: ["jquery"] }
    },
    paths: {
        "jquery": "node_modules/jquery/dist/jquery.min"
    },
    packages: [
        {
            name: 'bootstrap',
            location: 'node_modules/bootstrap/dist',
            main: 'js/bootstrap'
        }
    ]
});
```

`bootstrap/css/bootstrap.css` is loaded, but `jquery` dependency is not.

When we use `shim` and `paths`:

```
require.config({
    shim: {
        "bootstrap": { deps: ["jquery"] }
    },
    paths: {
        "jquery": "node_modules/jquery/dist/jquery.min",
        "bootstrap": "node_modules/bootstrap/dist/js/bootstrap",
        "text": "node_modules/requirejs-text/text"
    }
});
```

then `jquery` gets loaded, but `bootstrap/css/bootstrap.css` fails:

> text.js:307 GET http://localhost:9000/node_modules/bootstrap/dist/js/bootstrap/css/bootstrap.css 404 (Not Found)

As expected, path is constructed wrongly.

**Comment by ScottFreeCode** [comment]
I haven't tried paths for this sort of thing, but in my experience using `shim` with `packages` requires the entry in `shim` to match more than just the package name; I *think* `shim` has to refer to package.name + "/" + package.main.
```js
require.config({
    shim: {
        "bootstrap/js/bootstrap": { deps: ["jquery"] }
    },
    paths: {
        "jquery": "node_modules/jquery/dist/jquery.min"
    },
    packages: [
        {
            name: 'bootstrap',
            location: 'node_modules/bootstrap/dist',
            main: 'js/bootstrap'
        }
    ]
});
```

**Comment by nenadvicentic** [comment]
I've tested the example, it works like a charm now!

And to some extend it makes sense. `jquery` is dependency of main `.js` file, not whole package.

Thanks Scott!
