### ISSUE TITLE
use requirejs 2.2.0 require underfined (not always)

### ISSUE THREAD

**Issue by trojanliu** [requirejs/requirejs#1534]
```
require([./a.js], function() {
     var pageView;
     var PageClass = require("./a.js");
     if (PageClass) {
         pageView = new PageClass();
     } else {
         // window.location.reload();
     }
});
```
my web project is a single page WEB application.
sometimes, PageClass will be underfined, and sometimes is fine.  i dont know why?

I can see same problem in "https://github.com/requirejs/requirejs/issues/1260", but it seam that it has not give any solution.

**Comment by ScottFreeCode** [comment]
Is the first line of the code in question actually `require([a.js], function() {`, or is it actually `require(['a.js'],...` or `require(["./a.js"],...` (either type of quotation marks)? Without the quotation marks, `a.js` would be the property named `js` on an object named `a`, rather than the string "a.js" that `require` needs to name the module.

Consider also checking whether the module is consistently referred to with the file extension (".js"). Typically with AMD modules the extension does not need to be used in references to the module inside the code; that being said, if I recall correctly the extension is allowed but may change the behavior... and I'd imagine if it were used inconsistently it might cause discrepancies. Well, that's a hunch anyway; I'd have to run some tests to find out.

The issue might be neither of those two things, but they're worth double-checking.

**Comment by trojanliu** [comment]
oh, i am sorry that my description is not so rigorous.  it without the file extension (".js"). 

In fact the code like this: 
```
require(["js/newMainView"], function() {
     var pageView;
     var PageClass = require("js/newMainView");
     if (PageClass) {
         pageView = new PageClass();
     } else {
         // window.location.reload();
     }
});
```

**Comment by ScottFreeCode** [comment]
Cool; so, we know it's not just a typo of some sort in how it's written, or anything like that.

Next thing to double-check: whether it's really coming from RequireJS or is coming from Backbone (or how you're using Backbone; I'm not familiar enough to know if there are any potential problems there)... Here's a way to check:

```js
define([
    "backbone"
], function(
    Backbone
) {

    var export = Backbone.View.extend({

        initialize: function(options) {
            PageView.prototype.initialize.apply(this, arguments);
        }

    });
    
    if (!export) { throw new Error("Backbone didn't give us a valid object!"); }
    
    return export;
});
```
This will throw an exception with that pretty specific message if Backbone itself is returning `undefined`; if you don't get that exception and keep getting the undefined module, then we know it's a RequireJS issue. (I don't really know what exactly it's likely to be at this point, but it'll be nice to tell which library it involves.)

Unrelatedly (I don't expect this to fix it, although for all I know it might), you might consider changing the main code to either be like this:
```js
require(["js/newMainView"], function(PageClass) {
     var pageView;
     if (PageClass) {
         pageView = new PageClass();
     } else {
         // window.location.reload();
     }
});
```
(which is the AMD-ish way of `require`ing modules)
...or to be like this:
```js
require(["require", "js/newMainView"], function(require) {
     var pageView;
     var PageClass = require("js/newMainView");
     if (PageClass) {
         pageView = new PageClass();
     } else {
         // window.location.reload();
     }
});
```
(which is the way to be explicit that the modules are being written in Node.js style with an AMD wrapper, and is more portable if I'm not mistaken)

**Comment by trojanliu** [comment]
thanks for your advices. "PageClass" will be underfined not always the same.
```
require(["js/newMainView"], function(PageClass) {
     var pageView;
     if (PageClass) {
         pageView = new PageClass();
     } else {
         // window.location.reload();
     }
});
```

i will check later (whether it's really coming from RequireJS or is coming from Backbone.)

**Comment by trojanliu** [comment]
It may be not RequireJs 's bug.

Should be the problem of 'baidu map js script', 'newMainView.js' introduced 'baidu map js script', After I removed the corresponding script , the underfined didn't happen.

**Comment by jrburke** [comment]
Given the last comment, closing.
