### ISSUE TITLE
how to support dojo build layers? 

### ISSUE THREAD

**Issue by gbaumgart** [requirejs/requirejs#1540]
Hi,
I'd like to load pre-built layers into require js. Since there is isn't a simple require({cache:{mid:definition,...}}) function in require-js, I started hacking it for that: 

Somewhere in require.js#1761:  
req = requirejs = function (deps, callback, errback, optional) {

I write (more or less):

```
var _cached = null;
        if(deps && deps.cache){
            _cached = deps.cache;
        }

if(_cached) {
            for (mid in _cached) {
                context.defined[mid]=_cached[mid];
            }
            return;
        }

```

the only problem isn't that this doesn't end in a ordinary and fully evaluated requirejs module since the inner define per mid isn't called yet (i tried but no). 
Is there a trick to get to get this working? I am happy about getting anything working (knowing its dirty) but otherwise I end up in huge piles of work for double maintaining 2 build tasks.

thanks a lot, really

guenter

the typical pre-built layer from dojo looks like this: 

```
//>>built
require({
    cache: {
        "xwire/main": function () {
            define("dojo/_base/kernel xwire/Binding xwire/Source xwire/Target xwire/WidgetSource xwire/WidgetTarget xwire/EventSource xwire/DeviceTarget".split(" "), function (a) {
                return a.xnode
            })
        }, "xwire/Binding": function () {
            define(["dcl/dcl", "xwire/_Base"], function (a, d) {
                return a(d, {
                    declaredClass: "xwire.Binding", source: null, target: null, destroy: function () {
                        this.source && this.source.destroy()
                    }, trigger: function (e) {
                        this.target && this.target.run(e)
                    }, start: function () {
                        this.source &&
                        (this.source.binding = this, this.source.start());
                        this.target && (this.target.binding = this, this.target.start())
                    }
                })
            })
        }, "xwire/_Base": function () {

```

I tried also to override load but can't get it work either.

**Comment by gbaumgart** [comment]
I guess its a question for stack-overflow, right?

**Comment by jrburke** [comment]
It is better to call define() than to reach into the context.defined directly, that area is for storing the exports. So the trick is to call define() then call the context-specific require right after the define calls, so that context picks up the queued up modules, this comment talks about something similar:

https://github.com/requirejs/requirejs/issues/1536#issuecomment-217605817

Closing as a discussion ticket, but feel free to continue discussion here.
