### ISSUE TITLE
add cross origin attribute to root require

### ISSUE THREAD

**Issue by littlebee** [requirejs/requirejs#1550]
Hi, I've read the recommendations of  #687 and implemented an override of createNode that seems like it needs to be the first thing in the root require?   It works for all subsequent requires but the script tag for the root file itself and a couple of direct dependencies are injected without the attribute.

I'm currently using v 2.1.21 and loading the root file like this:
```php
<script data-main='views/appView' src='<? echo $cacheHost_JS ?>/js/lib/require-2.1.21.min.js'></script>
```
My createNode override looks like this:
```coffeescript
_originalRequireJsCreateNode = window.requirejs.createNode
window.requirejs.createNode = (config, moduleName, url) ->
  node = _originalRequireJsCreateNode(config, moduleName, url) 
  node.setAttribute 'crossorigin', 'anonymous'
  return node
```
Thank you~!

**Comment by jrburke** [comment]
There is an [onNodeCreated hook](https://github.com/requirejs/requirejs/blob/e97fe4dd894d8a07712156e17cefa28b954a9c3e/require.js#L1946) that can be used instead. If you want it to catch all script tags loaded by requirejs, it can be set up in a config object before the require.js script tag:

```html
<script>
// If requirejs is defined as an object before require.js loads, then require.js will treat it
// as an object to pass to requirejs.config() before doing any loading.
var requirejs = {
  onNodeCreated: function(node, config, id, url) {}
}
</script>
<script data-main='views/appView' src='<? echo $cacheHost_JS ?>/js/lib/require-2.1.21.min.js'></script>
```

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by littlebee** [comment]
Thank you for the fast reply!   That worked perfectly.  Thanks again for this amazing piece of code.

**Comment by marcelodeveloper** [comment]
This hook works fine @jrburke. Thank you! =)

**Comment by webgurumike** [comment]
This hook seems to work for all nodes except the data-main script. That's the one I needed to target.
