### ISSUE TITLE
Unable to find documentation on utility fucntions

### ISSUE THREAD

**Issue by beruic** [requirejs/requirejs#1555]
I'm working on a project where modules must be loaded dynamically.
I have found out that I can use `require.defined(name)` to check if a module has been loaded, but I cannot find the documentation for this, or any other utility functions that may prove useful. For example I am using `requirejs.s.contexts._.config.paths.hasOwnProperty(moduleName)` to see if a module is known, which is not optimal and wrong in some cases.

My app updates the config dynamically, so it would be nice with a way to test for module existence, that also checked for the file, but didn't necessarily load it.

**Comment by jrburke** [comment]
The documentation for that is not very good, sorry about that. This section talks about .defined() and .specified() in the context of the require passed to a plugin's load method, those are the same methods that are usable inside a module:

http://requirejs.org/docs/plugins.html#apiload

See the "parentRequire" section.

I think you want require.specified() if you just want to know that the dependency has been specified by a module as being needed, but may not be loaded yet. That requires the module that specifies that dependency to have been "activated", part of a top level require([]) call to load some code. For example, it will not catch dormant calls to define() before any top level require([]) call for them.

Closing as a discussion ticket, but feel free to continue discussion here.
