### ISSUE TITLE
waitSeconds expiring before config loaded

### ISSUE THREAD

**Issue by Slowlearneruk** [requirejs/requirejs#1557]
I have a project using requirejs - the entry point is a config file, init.js with a single dependency for main.js:

`require.config({`
`deps: ['main'],`
`paths: {`
`},`
`waitSeconds: 60`
`});`

main.js itself has a list of dependent files that themselves include others as is the way with require.js

The script is included in my page with the line:

`<script data-main='js/init.js' src='dist/require.min.js'></script>`

When I use the optimiser to compile a minified library, my starting point is the config file and it gives me a minified init.js that is about 200k. All good so far, however if I throttle the connection to say 20kb/s then what happens is the minified init.js takes longer than the default waitSeconds (7) and the load fails.

Can I suggest that we add another argument to the script inclusion point for require.js such that we can either override the waitSeconds:

`<script data-main='js/init.js' waitSeconds=0 src='dist/require.min.js'></script>`

Or alternatively to change the behaviour so that the timeout only applies to libraries included after the initial data-main library has been included.

**Comment by iamSokhi** [comment]
I am also facing same issue but in my case min file is around 1MB.
In min file, I have mentioned waitSeconds 0 to disable timeout.
However, min file itself gives timeout error for slow connection speed because default value is 7 seconds.

Currently, I am doing this

```js
<script type="text/javascript">
var require = {
      waitSeconds: 0
}
</script>
<script data-main="file.min.js?v=20" src="src/lib/require/require.js">
```

Is my approach correct?
Let me know if there is another better approach to resolving this.

**Comment by jrburke** [comment]
@iamSokhi has the correct way to approach the issue, by defining the config as a `require = {}` object before the script tag.

Note that if the network is really slow and the file is big, then the browser could decide to close the connection and time out. However, that would be a browser decision. In that case you would not see requirejs throwing a timeout error with the `waitSeconds: 0` as shown above.
