### ISSUE TITLE
how to handle the errors of require.js

### ISSUE THREAD

**Issue by zzzgit** [requirejs/requirejs#1558]
hello 
i want to handle the error which is thrown by `require.js`
think this case
if a file is not exist
i want to display a tips in the UI,not only a message in the console
so how could i handle the errors?

**Comment by jrburke** [comment]
There are two ways of [handling errors](http://requirejs.org/docs/api.html#errors):

For a global catch, you can define [requirejs.onError](http://requirejs.org/docs/api.html#requirejsonerror) to get notified of all errors.

For a particular `require([]) call`, providing a third argument as an [errback function](http://requirejs.org/docs/api.html#errbacks), it will be notified of an error with that require([]) call: `require(['a'], function(a) {}, function(error) {})`.

Closing as a discussion ticket, but feel free to continue discussion here.
