### ISSUE TITLE
requiring a module ending with ".js" will load a file directly

### ISSUE THREAD

**Issue by julmot** [requirejs/requirejs#1560]
There are many components for JavaScript out there ending with ".js" (note the dot). So, assuming you have the following configuration with a module "angular.js":

```javascript
require.config({
  paths: {
    "angular.js": "//cdn.jsdelivr.net/angularjs/1.5.5/angular.min.js"
  }
});
```

and requiring it using:

```javascript
require(["angular.js"], fn);
```
then Require.js will try to load the file "angular.js" instead of the module "angular.js" from jsDelivr.

I don't want to say that a file "angular.js" shouldn't be loaded at all. But from my point of view it should only be loaded if there isn't a module named like that. When having a module name ending ".json", ".com" or something else it will also not try to load the file directly, instead looks for the module.

**Comment by jrburke** [comment]
This is a historical choice by requirejs to treat [IDs that end in ".js" as a URL that does not go through the module ID-to-path config options](http://requirejs.org/docs/api.html#jsfiles). It is best to just use "angular" as the module ID and set up the paths config for "angular", then it will work.

Closing as working as designed, but if there was ever a 3.0 release or a different enough AMD loader that would not break backwards compatibility expectations I would revisit this choice. No plans to do so on the horizon though.

**Comment by julmot** [comment]
> if there was ever a 3.0 release or a different enough AMD loader that would not break backwards compatibility expectations I would revisit this choice. 

:+1: For rethinking this behavior. Don't you expect further releases?

**Comment by jrburke** [comment]
It is hard to contemplate larger major version releases with ECMAScript modules appearing so close to being implemented. The real issue though is how a native runtime loader would work in the browser and in Node, which is what would affect this ID resolution behavior, so I would really like to see how that shakes out and if there would even be a need for another requirejs major version release.

**Comment by artola** [comment]
I have a similar problem with `popper.js` required by `react-popper`, I managed to solve it using `map`:

```js
require.config({
  map: {
     "*": {
      "popper.js": "//cdn ... /popper.min.js"
    }
  }
});
```
As long as the dependency is "anonymous", it just works fine.
