### ISSUE TITLE
require from relative path

### ISSUE THREAD

**Issue by zhou7758437** [requirejs/requirejs#1567]
when use json plugin load data from relative path like
```
define([ "json!../../service/users/current"],function(user){
         // do sth
})
```

then it will throw 404 error

I think make this change can fix the bug

```
                    toUrl: function (moduleNamePlusExt) {
                        var ext,
                            index = moduleNamePlusExt.lastIndexOf('.'),
                            segment = moduleNamePlusExt.split('/')[0],
                            isRelative = segment === '.' || segment === '..';

                            //If this path does not contains  ../../
                            if(moduleNamePlusExt[index+1]=='/'&&moduleNamePlusExt[index-1]=='.'){
                                index=-1;
                            }

                        //Have a file extension alias, and it is not the
                        //dots from a relative path.
                        if (index !== -1 && (!isRelative || index > 1)) {
                            ext = moduleNamePlusExt.substring(index, moduleNamePlusExt.length);
                            moduleNamePlusExt = moduleNamePlusExt.substring(0, index);
                        }

                        return context.nameToUrl(normalize(moduleNamePlusExt,
                                                relMap && relMap.id, true), ext,  true);
                    },

```

**Comment by jrburke** [comment]
This sounds like a misconfiguration of the config for requirejs. A test case would help identify the core issue faster.

**Comment by zhou7758437** [comment]
@jrburke At first we set config  baseUrl  with 'js' folder for all the controllers, but with development of our project we add some require plugin into the project for loading css/json/html files. While those folders are already out of js folder and it is not very easy to move into js folder.
So we want to load file from  folder like ../../.../css  etc.

**Comment by jrburke** [comment]
Ah, so I think something like this should work, where a module ID prefix is set up to point to the area outside the baseUrl via a paths config, since module IDs that are outside the top of the module ID space cause problems:

```javascript
requirejs.config({
  baseUrl: 'js',
  paths: {
    service: '../../service'
  }
});

// Then later:
define([ "json!service/users/current", ....);
```

Closing as a discussion ticket, but feel free to continue discussion here.
