### ISSUE TITLE
RequireJS Needed New Feature to Unload the Modules

### ISSUE THREAD

**Issue by praneethkumarganji** [requirejs/requirejs#1568]
Hi ,

I am working on a project with Angular and RequireJS, 
RequireJS working great with dynamic Asynchronous Module Loader,

I am using Angular Views in 1st view loading dependent modules, in the 2nd view i still see view 1 dependent module js files on browser cache, is there a way to unload the modules from require js or 
any other way, 

**Needed solution for dynamically unloading the modules.**

Please suggest ...

**Comment by sumitkm** [comment]
Hi Praneeth,

You have hit the age old bug bear of web development - cache-busting. In development environment a hard refresh should do it or setting chrome/firefox to reload scripts when dev tools are open.

Once deployed to production you obviously can't tell all your users to do the same.

There are lots of ways to do it on production environment. The most common being - appending a hash to your file names, this is done via build tools like gulp or grunt.

I usually deploy to a new root folder everytime, where the folder name is timestamped. 

In both cases you have to modify the path to require js and require config as a part of the 'build' process.

I hope I got your question right and my answer is relevant.

Cheers,
Sumit.


-----Original Message-----

**Comment by jrburke** [comment]
That sounds like the core issue, so closing, but feel free to continue discussion here.
