### ISSUE TITLE
[Error: TypeError: Cannot call method 'substring' of undefined     at modLine 

### ISSUE THREAD

**Issue by CoderSquirrel** [requirejs/requirejs#1569]
I ran grunt at my project i got the error:

> { [Error: TypeError: Cannot call method 'substring' of undefined
>     at modLine (/myproject/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28040:48)
> ]
>   originalError: [TypeError: Cannot call method 'substring' of undefined] }

So i went and checked the line it is:

`contentLines[lineIndex] = line.substring(0, startIndex) + contentInsertion + line.substring(startIndex, line.length);`

inside the function `modLine` 

I search but i didn't found any releated error.
:/

**Comment by jrburke** [comment]
Closing in favor of https://github.com/requirejs/r.js/issues/924 since any fix would be in that repo.
