### ISSUE TITLE
Named callback function fires before all scripts are loaded

### ISSUE THREAD

**Issue by stoicbuddha** [requirejs/requirejs#1570]
When you define a function (as opposed to having it be anonymous) for the callback, that function runs pretty much instantly.  Ex:

```
requirejs([
  'jquery',
  'someplugin',
  'someplugin2'
],
  instantiation(),
  function(err){

    if(!window.playerLoadedOnError && JSON.stringify(err).indexOf("someplugin") > -1 || !window.playerLoadedOnError && JSON.stringify(err).indexOf("someplugin2") > -1){

      window.playerLoadedOnAdError = true;

    }

});

function instantiation(){
    console.log("function fired or whatever");
}
```

instantiation() will fire before jQuery loads.  If I instead make instantiation an anonymous function (function(){ console.log("somestuff"); }) jQuery (and other scripts) will be loaded before that function fires.

**Comment by chrisknoll** [comment]
Of course, you are triggering the function when you put function name followed by ().  If you want to pass a function to the parameter, don't invoke it with (), just pass the function name.

**Comment by chrisknoll** [comment]
Also, the fucntion passed as the 2nd parameter to requirejs will be invoked with parameters from the array of module IDs, so your instantiation function shoudl be decared as:
function instantiation($, p1, p2)

Where jquery module will be $, someplugin will be p1, and someplugin2 will be p2.

**Comment by stoicbuddha** [comment]
Ok.   I also solved it by shoving the function inside of an anonymous function.  So, there's that.

But ok, if that's the solution, cool!
