### ISSUE TITLE
urlArgs incorrectly processed parent folders

### ISSUE THREAD

**Issue by slanska** [requirejs/requirejs#1572]
When using urlArgs as a callback functions, scripts in parent folders are passed as incorrect url.
Example: current folder is 'app', 'jquery' is defined in config paths like 'jquery': '../bower_components/jquery/dist/jquery', so call is require(['jquery']). Loading dependency  (e.g. jquery) from 'app''s script - require(['jquery']...), urlArgs is called with url equal to 'app/../bower_components/jquery/dist/jquery'.

**Comment by jrburke** [comment]
I am not quite following, but it looks like that may be correct: the paths config was for '../bower_components/jquery/dist/jquery', and if the baseUrl is set to 'app', then that URL looks like it might be expected.

But I could be missing something. What URL where you expecting? Also showing the config that has the baseUrl and paths config, and what the printout of the parameters to the urlArgs function are.

Closing as a discussion ticket, but feel free to continue discussion here, and we can reopen if we discover something to fix in the code.
