### ISSUE TITLE
Unable to load AMD module in Node

### ISSUE THREAD

**Issue by KBPratap** [requirejs/requirejs#1575]
Hi,

I am trying to load a AMD module in Node. For which I followed the instructions available at http://requirejs.org/docs/node.html#2
which ends-up in following error `failed with error: TypeError: require.config is not a function`

Any idea what might go wrong?

**Comment by jrburke** [comment]
If this is in the top level module, use `requirejs` instead. `require` is probably the node require, which will not have the requirejs methods.

```javascript
var requirejs = require('requirejs');
requirejs.config({
});

// Start loading modules
requirejs(['main']);
```

Closing as a discussion ticket, but feel free to continue discussion here.
