### ISSUE TITLE
requirejs.optimize problem, optimizer:'none' not respected

### ISSUE THREAD

**Issue by ericnewton76** [requirejs/requirejs#1578]
Using npm gulp-requirejs-optimizer which uses requirejs@2.2.0 i'm getting a problem with the optimizer where its not respecting my optimizer:'none' value.  _(NOTE: there is another npm gulp-requirejs-optimize without the R, that package isn't maintained anymore and should be deprecated by npm.org)_

Somewhere within the optimizer, the value is spontaneously changing from none to uglify.

See https://github.com/jlouns/gulp-requirejs-optimize/issues/22 that I filed for more explanation.

Over there, within gulp-requirejs-optimizer:index.js, I added a console.log of the optimizeConfig options being passed into requirejs.optimize function clearly showing the value of optimize:'none' being passed into the function.

**The core issue:** the main.js file that i'm trying to build never gets uglified ironically.

**Comment by ericnewton76** [comment]
I'm creating a sample project momentarily and will upload to github soon

**Comment by ericnewton76** [comment]
Repo is at https://github.com/ericnewton76/debug-gulprequirejsoptimize-issue22

Will update this post when completely finished.

**Comment by jrburke** [comment]
Looking at the this line:
https://github.com/ericnewton76/debug-gulprequirejsoptimize-issue22/blob/master/gulpfile.js#L74

I believe that should be `optimize: 'none'`, no "r" at the end of optimize.

Closing as a discussion ticket, but feel free to continue discussion here.
