### ISSUE TITLE
r.js from npm do not support the "=>" grammar from ECMAScript 5.

### ISSUE THREAD

**Issue by piratf** [requirejs/requirejs#1580]
Write a function with "=>" could maintain the "this" environment right automatically even in the callback situation in third-party event libraries.

a simple example for this kind of function is:

```javascript
// original type
function (value) {
    console.log(value);
}
// '=>' type
(value) => {
    console.log(value);
}
```

When I'm using r.js from npm, It reported an error for the "=>" part, and refuse to uglify them, Would you help us to fix this issue? Thank you for made this wonderful tool.

**Comment by jrburke** [comment]
I just pushed an update to r.js, tracked in https://github.com/requirejs/r.js/issues/927 to update uglifyjs to the latest release version.

You can try it by using the master snapshot:
https://raw.githubusercontent.com/requirejs/r.js/master/dist/r.js

If that works for you then that would be good to know.

However, uglifyjs does not support all of the ES2015+ grammar, so it still may have trouble with arrow functions.

If you are wanting to use more of the ES2015+ grammar, then you might take a look at https://babeljs.io/blog/2016/08/30/babili to see if that will work for your case. If you use that other minifier, just set the  r.js build config to be `optimize: "none"`, and then run that minifier after the r.js build step yourself.

Closing now, hopefully addressed by https://github.com/requirejs/r.js/issues/927 but we can reopen if further discussion points to another code change that can be done.
