### ISSUE TITLE
Requirejs within WordPress

### ISSUE THREAD

**Issue by Markj89** [requirejs/requirejs#1586]
I'm not sure if this issue has been resolved, however; I've tried implementing this within WordPress and with some minimal success; the browser would timeout before loading all scripts. Im not sure if anyone else had this issue before, but now i've had to wp-enqueue all scripts dynamically.

Is there any reason why the browser would time out before finishing to load all dependencies?

**Comment by sumitkm** [comment]
Hi, I have had genuine require js timeouts on slow computers. You can try the waitSeconds property on your require config as explained here... http://requirejs.org/docs/api.html#config 

If a value of say 20 seconds doesn't do it, I'll say some of the modules you are trying to load don't like the AMD way of getting loaded.

**Comment by Markj89** [comment]
At the moment, I am using Kendo, Moment and Moment-timezones, they were originally part of the map:{} once I implemented this into WordPress, however, I changed and am trying to use the waitsecond parameter and the Optimizer.

**Comment by sumitkm** [comment]
I haven't used Kendo, but Moment definitely works well with RequireJS.
From the looks of this example, Kendo shouldn't give you too much trouble either
http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-requirejs#use-bundle-scripts-with-requirejs

Let us know how it goes.
Cheers
