### ISSUE TITLE
Performance in project with large number of requires (1000+)

### ISSUE THREAD

**Issue by sheebz** [requirejs/requirejs#1591]
I am seeing a performance problem with a project that has 1000+ require calls.  It seems like there is at least a minus 8 microsecond perf hit on every call, which can be much bigger depending on the size of the module etc... Are there any guidelines for this type of project?  Does using require vs. define sytax have an impact at this level?   - e.g.

`define(['require'], function(require){
var foo = require('bar');
`
vs
`define(['foo','bar'], function(foo,bar){}`

It's a fairly vague question, but any guidance on using require on very large project with 1000+ modules would be appreciated.  Thanks in advance.

**Comment by sumitkm** [comment]
Hi Rob,

Are you using the r.js compiler to pack the modules up or these are
1000+ on-demand calls to the web-server?

Regards,
Sumit.


On Mon, Sep 26, 2016, at 10:22 AM, Rob Schieber wrote:
> I am seeing a performance problem with a project that has 1000+
> require calls.  It seems like there is at least a minus 8 microsecond
> perf hit on every call, which can be much bigger depending on the size
> of the module etc... Are there any guidelines for this type of
> project?  Does using require vs. define sytax have an impact at this
> level?   - e.g.
> define(['require'], function(require){ var foo = require('bar');
>  vs
> define(['foo','bar'], function(foo,bar){}
> It's a fairly vague question, but any guidance on using require on
> very large project with 1000+ modules would be appreciated.  Thanks in
> advance.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/requirejs/requirejs/issues/1591

**Comment by sheebz** [comment]
Hi the modules are packed using r.js.  The links you posted don't seem to be valid.

**Comment by jrburke** [comment]
`define(['foo','bar'], function(foo,bar){}` will likely perform better than the first example since the module value is passed in and is just a local variable reference vs a function call as in the first case. The first case will have already had done the work of getting the imported module exports all set up anyway too, the `require('bar')` inside the define factory function just gets the export, does not delay execution of the import until that call.

However, I would consider that a micro optimization to pursue as a last resort. I expect larger perf gains by breaking up the 1000 modules into grouped chunks (or "code splitting" as it is sometimes referred to now) that can be loaded as needed via triggered `require([])` calls as that can avoid JS transmission, parse and eval times.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by sheebz** [comment]
Thanks James.  Is code splitting something that I would implement when running optimizer? The way I think I understand is say I have modules A,G,Q which have dependencies listed -  
A->B,C,D,E,F,G,Q
G->B,C,D,H,I
Q->B,C,D,R,S,T
So in above case would goal be to remove G,Q as dependencies in optimizer?

**Comment by jrburke** [comment]
You can specify build bundles in the optimizer config, and usually that is paired with some runtime `require([])` calls at certain app loading points, for example in a router type of module, or as the user taps on a button to go to a new piece of functionality.

Unfortunately the docs around this are a bit lacking. [example-multipage](https://github.com/requirejs/example-multipage) is structured around an app that has multiple pages, but with a common set of modules bundled together and page specific modules that are bundled together, and how the r.js build options exclude the common set from the page specific sets. So it is useful to look at for that sort of "common bundle, exclude from page or route specific bundles" approach.

[example.build.js](https://github.com/requirejs/r.js/blob/5d84eeae4fc92c45c71a68536acaad6495df769e/build/example.build.js#L347) mentions all the possible build config options, but for code splitting the `include` and `exclude` options for a `modules` entry are the main things used.

Note that `exclude` of a previously named `modules` bundle will exclude all that was built into that bundle, and things that you want to `exclude` from other bundles should be defined before the other bundles.

The other route to go if you don't want to have to rework your code too much for loading different bundles on demand via well placed `require([])` calls is to use [bundles config](http://requirejs.org/docs/api.html#config-bundles), which will map modules IDs in a bundle to a bundle module ID. The downside with that approach is needing to list all the module IDs that are in a bundle in the config. With 1000+ modules, that could be a significant amount of config code to ship to the client. The optimizer can help automate the construction of the bundles config, but the size of that config could still be a concern.
