### ISSUE TITLE
Closure compiler.js

### ISSUE THREAD

**Issue by houd1ni** [requirejs/requirejs#1592]
It seems, that the optimizer uses Java version of Google closure compiler.

How do you feel about using its JS version?

**Comment by jrburke** [comment]
Some links for future reference:

* [Announcement blog post](https://developers.googleblog.com/2016/08/closure-compiler-in-javascript.html)
* [GitHub repo](https://github.com/google/closure-compiler-js)

I would like to move away from bundling minifiers with the r.js optimizer, as it is a dependency that can change and some people would like particular versions of it. The Java version of Closure Compiler is not embedded, and while there is code to call out to it in the r.js optimizer, I would like to move away from that. Plus this JS version of Closure Compiler is still considered experimental.

Instead, people can use the r.js optimizer with `"optimize": "none"` then call the optimizer of their choice in their build script after calling r.js.

The tooling around JS has gotten much more expansive and easier to use particularly with node than when r.js was originally started. I would like to see the r.js tasks focus on the special things it can do, namely module tracing and formatting for bundling. [amodro-trace](https://github.com/amodrojs/amodro-trace) is what I would imagine r.js would look like if it was started today.

**Comment by houd1ni** [comment]
True! Thank you very much!
