### ISSUE TITLE
escape white space mids ?

### ISSUE THREAD

**Issue by gbaumgart** [requirejs/requirejs#1596]
Hi,
how i can make require-js supporting whitespaces ? It doesn't auto-escape it and I am wondering this on purpose? 

I could fix this on my own but was wondering what the official way is for that...

thanks already,
g

**Comment by jrburke** [comment]
It was on purpose, the original CommonJS specification around module IDs did not support them and it seemed like it would run into problems when trying to map it to storage facilities (like file system, database). No plans to support spaces now. Trying to support it would likely take changes to require.js and the r.js optimizer.

**Comment by gbaumgart** [comment]
no, problem. fixed in my version.
problem is that modules can exist then only in a narrow web world. i came along cases where people pick those from their user folder. for instance in electron apps, desktop apps, etc...pity
