### ISSUE TITLE
load time out bug!!The config waitSeconds can not work;

### ISSUE THREAD

**Issue by fucongcong** [requirejs/requirejs#1597]
![7d33cd0983b5f78a8bca6899c6cb245d](https://cloud.githubusercontent.com/assets/8229954/19434825/33a08eb8-949a-11e6-84bc-378364ddc479.jpg)
![3089a102-6d62-4489-917c-e4f6a202261a](https://cloud.githubusercontent.com/assets/8229954/19434762/e7d3c61c-9499-11e6-8d1c-1ab7d8f3134b.png)
![d2dc452b-a5fa-4002-9012-5fa30590134f](https://cloud.githubusercontent.com/assets/8229954/19434768/ee77a1c8-9499-11e6-86ff-6d634a189605.png)
![8218e5c5-c2b5-4be6-9014-9780787190ef](https://cloud.githubusercontent.com/assets/8229954/19434794/10c65b3e-949a-11e6-9bf2-97bf4eaa9102.png)

**Comment by fucongcong** [comment]
add

**Comment by fucongcong** [comment]
![4d291442-d2d5-4c99-af84-87bfdec6e423](https://cloud.githubusercontent.com/assets/8229954/19434858/601b82fe-949a-11e6-8dd0-807e6165456b.png)

only app.js .No app modules

**Comment by fucongcong** [comment]
![15cffa37-1944-47f3-aae1-b02e15e7ee8f](https://cloud.githubusercontent.com/assets/8229954/19434895/98b96568-949a-11e6-8c28-3ed10a795002.png)

**Comment by jrburke** [comment]
It sounds like the waitSeconds is not being set before fetching of modules starts. You can make sure it is set up front by 

```html
<script>var require = { waitSeconds: 0 };</script>
<script data-main="" src="require.js"></script>
```

That should fix the issue, this sort of situation has come up before. However, leave a comment if it does not.
