### ISSUE TITLE
base64.js as a filename causes silent failure.

### ISSUE THREAD

**Issue by sn0wmatt** [requirejs/requirejs#1600]
Having base64.js as a filename, included in require_config.paths causes a silent failure of controller loading.

**Comment by jrburke** [comment]
There is no special casing for 'base64' for a module name in the loader. I suspect it is another problem. If you have a test case I can try, then we should be able to figure it out.

Going to close for now as a discussion ticket, but feel free to continue discussion here, and we can reopen it if we find a fix is needed in the loader.
