### ISSUE TITLE
RequireJS set CDN active globally

### ISSUE THREAD

**Issue by johnib** [requirejs/requirejs#1603]
I'm using RequireJS in my client-side project, it is a large-scale project.
When the site is deployed to my production environment, I would like the bundled files to be downloaded from my CDN servers, and if CDN is not responding then from my server directly.

For that, my `requirejs.prod.config` looks like this:

    // prod config
    require.config({
        baseUrl: '.',
        paths: {
            main: [cdnBaseUrl + 'index', 'index'],
            main2: [cdnBaseUrl + 'index2', 'index2'],
            main3: [cdnBaseUrl + 'index3', 'index3'],
            main4: [cdnBaseUrl + 'index4', 'index4'],
            main5: [cdnBaseUrl + 'index5', 'index5'],
            // more bundle files
        }
    });

**The CDN endpoint is the same for all my modules.**

How could I keep my `requirejs.dev.config` without modifying it with some stupid regex's and still apply the same behavior?

    // dev config
    require.config({
        baseUrl: '.',
        paths: {
            main: 'index',
            auth: 'plugins/auth/auth',
            authController: 'plugins/auth/authController',
            logger: 'services/logger',
            constants: 'common/constants'
            // many more modules
        }
    });

I'm looking for something like this:

    // dev config that applies to production aswell
    require.config({
        baseUrl: '.',
        cdnEndpoint: 'https://cdn.endpoint',  // <----- this is the change
        paths: {
            main: 'index',
            auth: 'plugins/auth/auth',
            authController: 'plugins/auth/authController',
            logger: 'services/logger',
            constants: 'common/constants'
            // many more modules
        }
    });

This will allow me to remove all the regex's definitions I have in my `replace grunt task`, which is not maintainable.

**Comment by jrburke** [comment]
No plans to add this sort of config, but if the dev config is not used for builds (which sounds like it may not if you have multiple bundles), then you can imperatively build up the require.config() in code, something like this:

```javascript
var paths = {
  // set up dev config here.
};

// Write out "true" for isProd in the prod case using grunt task
var isProd = false;

if (isProd) {
  Object.keys(paths).forEach(function(key) {
    var path = paths[key];
    paths[key] = [cdnEndpoint + path, path];
  });
}

require.config({ paths: paths });
```

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by johnib** [comment]
1. The require.config file is actually in use in my case and I use the 'bundles' feature. 

2. I prefer not doing these kind of things in my project. I would very much like to have it supported in requirejs. 

How about I send a pull request for that?

**Comment by jrburke** [comment]
No plans to add this, it also means propagating it to the other requirejs loaders. If you use the require.config call in dev as a start, you can call that, then below that call, access `requirejs.s.contexts._.config.paths` to get the paths config already registered, and could use a code snippet like above to do the automated conversion to array based paths config, and call requirejs.config() then with that paths config.

**Comment by johnib** [comment]
Thanks that'll help!
