### ISSUE TITLE
Recommended to add module.exports support

### ISSUE THREAD

**Issue by yuchonghua** [requirejs/requirejs#1609]
Recommended to add module.exports support
@jrburke  @ivaylo5ev  Do not know what you think

Add the following code to line 38
```JavaScript
	function inherit(p) {
		if(Object&&Object.create){
			return Object.create(p);
		}else{
			var r = function r(p) {};
			r.prototype=p;
			return new r();
		}
	}
```

Add the following code to line 1573

```JavaScript
				var module = window.module;
				window.module = inherit(null);
				window.module.exports = inherit(null);
				if (module&&module.exports) {
					define(moduleName,[],function(){
						return module.exports;
					});
				}
```

Add the following code to line 1911

```JavaScript
		window.module = inherit(null);
		window.module.exports = inherit(null);
```

![Add the following code to line 38](https://cloud.githubusercontent.com/assets/17898715/20213393/6d48649e-a843-11e6-8310-eacc9ca81d76.png)
![Add the following code to line 1573](https://cloud.githubusercontent.com/assets/17898715/20213392/6d447b9a-a843-11e6-8c52-ab570d3d0062.png)
![Add the following code to line 1911](https://cloud.githubusercontent.com/assets/17898715/20213394/6d6851e6-a843-11e6-99b1-c59f9969df47.png)

**Comment by yuchonghua** [comment]
@jrburke @ivaylo5ev Do not know what you think

**Comment by jrburke** [comment]
An AMD module can use `module.exports` today by using the [sugared CommonJS call signature](http://requirejs.org/docs/whyamd.html#sugar):

```javascript
define(function(require, exports, module) {
  module.exports.color = 'blue';
});
```

A globally visible `module` property would not be viable to support, since each module needs its own specific instance of it.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by ScottFreeCode** [comment]
> A globally visible  module  property would not be viable to support, since each module needs its own specific instance of it.

I'm not sure I entirely understand the code suggested in the OP, but couldn't `exports`/`module.exports` be retrieved as the module value and a new `module`/`exports`/`module.exports` be set up in a hook in between modules triggered by the same events used for shim handling and/or loader plugins?

**Comment by jrburke** [comment]
This issue is that some modules use `module.exports` after initial script execution.

**Comment by ScottFreeCode** [comment]
Woah. I'd seen modules that call `exports.<various functions>` in their functions (basically, using some of their public API in their implementation), but until now I had not realized the implications in terms of how `exports`/`module.exports` must be implemented.

**Comment by fanyonglong** [comment]
box.js
```js
const fork = require("./framework/fork");
const Math = require("./framework/math");
const Solver = require("./framework/solver");
const Joint = require("./joints/joint");
const RevJoint = require("./joints/revjoint");
const RopeJoint = require("./joints/ropejoint");
const SpringJoint = require("./joints/springjoint");
const WheelJoint = require("./joints/wheeljoint");
const Body = require("./objects/body");
const Circle = require("./objects/circle");
const Polygon = require("./objects/polygon");
const {Shape, AABB} = require("./objects/shape");

module.exports = {
	fork,
	Math,
	Solver,
	Body,
	AABB,
	Shapes: {
		Shape,
		Circle,
		Polygon,
	},
	Joints: {
		Joint,
		RevJoint,
		RopeJoint,
		SpringJoint,
		WheelJoint,
	},
};
```   

var commonjs=requirejs.s.newContext('commonjs')
       commonjs.configure({
               baseUrl:"https://cdn.jsdelivr.net/npm",
               paths:{
               }
        });
        commonjs.load=function(id,url){
             $.ajax({
                 type:'get',
                 url:url,
                 dataType:"text"
             }).then(function(code){
                    define(new Function('require','exports','module',code));
                    commonjs.completeLoad(id);
             })
        }
        commonjs.require(['./boxjs@1.2.3/src/box'],function(box){
            console.log('box',box)
        })
