### ISSUE TITLE
RequireJS loading fault silently fails and hides JS errors. 

### ISSUE THREAD

**Issue by andymonis** [requirejs/requirejs#1611]
I have been investigating an intermittent fault with my project loading for a long and really struggled to pinpoint the problem. This is caused by RequireJs failing to load a file, because of a JS error on the page. However the JS error was not shown in the console, so it appeared as if RequireJs was just sitting there. 
The actual fault was very easy to resolve once I understood the problem, two files we actually required in a specific order, so adding a dependency resolved this. 
However the nature of the fix below is more to do with helping Developers at design time, to understand the problem. 

The fix would appear directly after line 691 in the debug version of 2.3.2 and would look something like this

/*
  Andy Monis: 10/11/2016
  Added an explicit check for mod.error
  There are cases where all other paths are ignored and the load process fails. Yet there were javascript errors usually caused by an out of sync dependency. 
*/
if( mod.error ) {
  return onError( modId + ":" + mod.error.message );
}

This change has no impact on the loading mechanism and is purely to aid developers when building complex require solutions

**Comment by jrburke** [comment]
That line is in the checkLoaded function, which is called frequently to check the state of loading of all entries in the registry. I am concerned that putting the check there may result in emitting multiple errors for the same error.

I would have expected the error pathway to be triggered in some other way, but there could definitely be an issue with the error mechanism. A small test case that demonstrates the issue might point to how best to fix it and also give a base for a new unit test to confirm it stays fixed.

Another solution could be to try [alameda](https://github.com/requirejs/alameda). It has more modern internals and may handle the error cases better.

Going to close this for now as a discussion ticket, but we can easily reopen if we can isolate the specific error case more so a unit test can be set up to test any fix.

**Comment by jslegers** [comment]
> Going to close this for now as a discussion ticket, but we can easily reopen if we can isolate the specific error case more so a unit test can be set up to test any fix.

### Use case 1

Why about [this issue](https://github.com/requirejs/r.js/issues/962)?

Executing `require(["app/js/main"])` silently fails if the path to the file is correct but you happen to have called the module in that file `js/main` instead (which was the case after bundling & minification with r.js).

I finally managed to solve my problem by changing the `name` property in my r.js config, but the silent fail of `require(["app/js/main"])` gave me a lot of headaches that might have been avoided with proper error handling.

### Use case 2

What about files that are incorrectly minified with UglifyJS? It happened to me a few times that UglifyJS choked on a minor typo that didn't get picked up by either my IDE or my browser. In such a case, it produces a file that contains nothing but `undefined`. 

I would expect RequireJS to throw a error when it tries to load a module from a file that contains only `undefined`, but it doesn't. It is only when I try to access a property of that module that errors are being thrown, which can result in some pretty confusing debugging!

**Comment by jrburke** [comment]
For case 1, two things to look for:

* I expect that since that module ID does not exist in a built file, it would try to fetch it, and the web browser developer tools would show a network error for the fetch. Should be in the Network tab for sure but depending on the browser may also log a console error.
* Does `require(['app/js/main'], function() {}, function(error) { alert(error); }})`, does that surface the error? Since the loader is async a function callback as the third arg to require() is needed.

For case 2: a file with just `undefined` in it is valid JS, and requirejs cannot know the intention of an actual module body. It could be that the developer decides in some cases that the fetch should basically be an empty file, but still wants the dependency treated as resolved.
