### ISSUE TITLE
Using a folder name with a dot causes requirejs not to load the proper dependency

### ISSUE THREAD

**Issue by raisen** [requirejs/requirejs#1613]
If I have a config such as below:

```
requirejs.config({
  baseUrl: '/',
  paths: {
    datatables: 'bower_components/datatables.net/js/jquery.dataTables.min'
  }
});
```

requirejs tries to load `/datatables.net.js` instead of the full pathname. If I replace ".net" for something else that doesn't look like a hostname, it works fine.

**Comment by jrburke** [comment]
I tried with a local project that set 'datatables' to the same value as above, and it resolves correctly for me with requirejs 2.3.2 when I `requirejs(['datatables'])`. Perhaps there is more info, maybe a sample project you can put up that shows the issue.

Closing for now as a discussion ticket, but we can reopen if further discussion uncovers something that needs to change in the code.
