### ISSUE TITLE
Relative ids from module defined in path

### ISSUE THREAD

**Issue by xcoderzach** [requirejs/requirejs#162]
requiring modules from within a module defined in paths doesn't work properly.

for example with the configuration:

``` javascript
require.config({
  baseUrl: "/javascripts"
, paths: {my_module: "lib/my_module/lib/my_module" }
})
```

``` javascript
// In my_module.js 
define(["./dep"], function(dep) {

})
```

It tries to load /javascripts/dep rather than /javascript/lib/my_module/lib/dep.  

  I'm not sure if this is intended, but it would be nice if it loaded it relative to the actual url rather than the alias.

**Comment by adrian-moisa** [comment]
Thanks @totty90 ! I finally get it, after reading the documentation about module IDs, relative paths and packages I managed to get the best of all.

Instead of:

    paths: {
        'inputs': 'engine/inputs/inputs',
        ...
    }
which doesn't load relative modules inside module: `engine/inputs/inputs.js`:

I used:
    packages : [
        {
            name: 'inputs',
            location : 'engine/inputs',
            main : 'inputs'
        },
        ...
    ]

and inputs.js:

	define([
		'./inputContexts', // Relative (used locally, no need to cluter main.js with this module)
		/* '../src/engine/inputs/inputsContexts', // Absolute paths worked, but they are long and ugly */
		'constants' // Defined in paths (This is best suited for modules required in multiple places)
	], function(
		inputContexts,
		constants
	){
		...
	});
