### ISSUE TITLE
Question about bundling Babel modules

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/requirejs#1621]
WRT this issue https://github.com/babel/babel/issues/4990

What's happening is that I need certain Babel deps in the front-end - the thing is that these Babel deps don't appear to packaged in ways that front-end code used to be packaged into a single .js file. It appears as though Babel is expecting people to use tools like `Browserify` or `Webpack` to trace NPM deps and turn them into front-end modules.

I am trying to figure out how to bundle the `babel-runtime` NPM package into a dependency that RequireJS can understand. Note that `babel-runtime` depends directly on two other NPM packages.

Normally I use CDNs to pull in this type of code, but it doesn't look like babel-runtime is available via CDN. (One would think that we wouldn't need any Babel deps on the front-end, but turns out it looks like we do, the way Babel is set up.)

I haven't been doing much front-end development of late, and I have this older project that pairs RequireJS with React and Babel.

I simply do not know how get these NPM packages into a bundle that I can load with RequireJS. Any idea how this can be done? Should I just move to Webpack for this project?

**Comment by ORESoftware** [comment]
I have this:


```js
requirejs.config({
    enforceDefine: false,
    waitSeconds: 7,
    baseUrl: '/',
    paths: {

        //CDN
        'async': '//cdnjs.cloudflare.com/ajax/libs/async/1.5.0/async.min',
        'jquery': '//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min',
        'flux': '//cdnjs.cloudflare.com/ajax/libs/flux/2.1.1/Flux.min',
        'underscore': '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min',
        'react': '//cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react',
        'react-dom': '//cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react-dom',
        'socketio': '//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.7/socket.io.min',
        'lodash': '//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.7.0/lodash',
        'babel': '//cdnjs.cloudflare.com/ajax/libs/babel-core/6.1.19/browser',
        // 'babel': '//cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.19.0/babel',

        //local
        '@Accordion': 'js/react-components/AccordionComp',
        '@AccordionSection': 'js/react-components/AccordionSection',
        '@ReactController': 'js/react-components/react-controller',
        'TestFileSuite': 'js/react-components/TestFileSuite'
    },

    'shim': {

        'underscore': {
            'exports': '_'
        }
    }

});
```

but it doesn't seem to load the babel dep from the CDN, not sure if that's even the right way to do it.

**Comment by jrburke** [comment]
Babel users typically use webpack, that pathway has lots of support infrastructure, so I suggest going that route if using Babel.

**Comment by ORESoftware** [comment]
Sure, but pretty much all React users have become Babel users due to the way things are going. Any plan to make RequireJS work better with Webpack?

**Comment by ORESoftware** [comment]
I am still big on hot-reloading and that is not very easy with Webpack. What might be cool would be to mix RequireJS's bundle features with Webpack somehow.

**Comment by ORESoftware** [comment]
Basically, Webpack is more or less necessary to bundle up NPM dependencies, but after that you're free to use RequireJS if you want. One feature that I like about RequireJS is the fact that you can load one module at a time. 

TBH I never fully figured out how to use RequireJS's production bundles feature, it was too complicated. But the idea was that if you were in production and you had bundles and you did require('x/y/z'), RequireJS would see if that file was part of a bundle and it was, it would load that bundle instead of the file. In development, it would just load that one file.

I don't know any other system can have that feature except RequireJS, and it could be powerful. Maybe you tell me. It would be nice to see an article about how to marry RequireJS with Webpack for great good, but maybe it's just not that much of a win. IDK.

**Comment by ORESoftware** [comment]
@jrburke ok so I did a little experimentation, using Webpack + RequireJS

You should be able to bundle NPM dependency trees into AMD deps like so with Webpack, at least this is one way to do it:

// In webpack.config.js



```
module.exports = {
    entry: {
      index:  './server/lib-es5/pages/index/app.js',
      results:  './server/lib-es5/pages/results/app.js',
      'amd-deps': './server/lib-es6/pre-bundles/amd-deps.js'
    },
    output: {
        path: __dirname + '/server/public/bundles',
        filename: '[name].js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                include: __dirname,
                loader: 'babel-loader',
                exclude: /node_modules/
            },
            {
                test: /\.json$/,
                include: __dirname,
                loader: 'json-loader',
                exclude: /node_modules/
            }
        ]
    },
    plugins: []
};

```

the amd-deps.js file looks like this (just a series of define blocks of all the deps you want):


define('underscore', function(require){
    return require('underscore');
});

console.log('underscore is defined');

define('babel-runtime', function(require){
    return require('babel-runtime');
});

console.log('babel-runtime is defined');

define('babel-polyfill', function(require){
    return require('babel-polyfill');
});

console.log('babel-polyfill is defined');


however, even though the front-end loads the above code (we see all 3 log statements in the web console), RequireJS still uses AJAX to search for the deps and gets a 404 for each. I think I have seen this problem before..do you happen to know what it might be?

Just want to experiment a bit with RequireJS + Webpack + Babel before throwing in the towel!

**Comment by tecnocrata** [comment]
Hello,
My two cents here, my best recommendation is to migrate completly to webpack if you are trying to use react.
Please read this 'old' but vigent article: 
http://j-query.blogspot.com/2015/06/from-requirejs-to-webpack-part-1-reasons.html
