### ISSUE TITLE
Wiki: Plugin list is broken

### ISSUE THREAD

**Issue by Offirmo** [requirejs/requirejs#1622]
the main page https://github.com/requirejs/requirejs/wiki and the official doc http://requirejs.org/docs/plugins.html both link to a "list of require.js plugins"

However both links are dead.

Searching the wiki, I couldn't find this precious resource.

Could someone restore this list ?

**Comment by jrburke** [comment]
Thank you for pointing out it had been accidentally removed, the page has been restored.

**Comment by Offirmo** [comment]
I'm tired of webpack and having a look at requirejs again ^^

**Comment by Offirmo** [comment]
Thanks for the great work !

**Comment by chalchis** [comment]
I know this is not a forum, but what was your problem with webpack?
Since I plan to go with webpack

**Comment by Offirmo** [comment]
![heap](https://cloud.githubusercontent.com/assets/603503/21318948/988f0154-c60b-11e6-88a8-c4a1f10dc2b7.png)

* Our unit tests crashing out of memory :-(
* 1min+ start time of the unit tests
* 30s+ for a live reload
* hot reload comes and go
![hot-reload](https://cloud.githubusercontent.com/assets/603503/21319015/c959a028-c60b-11e6-856d-e05aa72334ec.png)
* hot-reload activated server crashes on syntax error (typescript loader)

**Comment by Offirmo** [comment]
Sorry this is completely a rant.

I must outline that I'm in a team of 7 including 5 senior web dev, and nobody is eager to dive in webpack to fix the config, so it's not just me :-(
