### ISSUE TITLE
Dependencies not invoked with complex path on a shim

### ISSUE THREAD

**Issue by sanewell92** [requirejs/requirejs#1628]
## Deps not provided when using ../ paths in shims

This issue was brought up when I was working on porting an old ASP system to start using requirejs for its front end. There's a script, let call it `dynamicScript.aspx`, that has been provided to my company that runs a service `blinky`.

Now, I am not allowed to touch this dynamic script. It needs to run server code before being served up, and it **can't live in the same place as the project** - apparently multiple projects request this file and we want this file to be a level above the other files.

This [github repo](https://github.com/sanewell92/TestRequireDynamicLoading) demonstrates the issue in a concise way, stripping out a lot of the other details

Here's the meat of the config for require (specified in a global `require` variable)
```JS
paths: {
  jquery: "jquery.min",
  jqueryui: "plugins/jquery-ui",
  blinky: "../dynamicScript.aspx?dynamic=1"
},
shim: {
  "../dynamicScript.aspx?dynamic=1": ["jquery", "jqueryui"]
}
```

Whenever the module `blinky` is requested it errors out - sometimes `jQuery` is not defined, or `widget` is not defined.

Interestingly, explicitly adding `jquery` and `jqueryui` as dependencies for `index.js` seems to resolve the issue. However when requesting the extension blinky to be ran, shouldn't it also run jquery and jqueryui and provide those to blinky? Why would the dependency list of `index,js` affect the shimmed module?

**Comment by jrburke** [comment]
Looking at that config, the `shim` config should use the module ID and not the path for the configuration. So something like:

```javascript
shim: {
  "blinky": ["jquery", "jqueryui"]
}
```

Closing as a discussion ticket, but feel free to continue discussion here and we can reopen if we discover a problem.
