### ISSUE TITLE
How does requireJS handle triangle imports?

### ISSUE THREAD

**Issue by TheInvoker** [requirejs/requirejs#1629]
Using requireJS for AMD, what if I have a case where I have 3 files, A, B, C.

A imports from B and C. And C imports from B.

If I run A, will it download B twice?

**Comment by chrisknoll** [comment]
It won't download twice, but you should be aware of circular dependencies (CD) in your code.  Despite what you may have read about CD being bad design, I have them in my own code so I can understand where they are necessary.  

In my experience, if you use the standard AMD definition:

```
define (['dep1','dep2'], function (d1, d2) {
// use code here
));

```

But thep deps involve some CD, then you need to use the CommonJS format (http://requirejs.org/docs/commonjs.html) and do the following:

```
define(function (require, exports, module) {
var dep1 = require('dep1');
var dep2 = require('dep2');
});
```

Seems that the way the dependencies are resolved using the CJS format works better for circular references than if they were requested inline in the define() call.
