### ISSUE TITLE
How to use different hostnames?

### ISSUE THREAD

**Issue by trusktr** [requirejs/requirejs#1633]
Seems like when a file is requested with a leading `/` or a protocol, then the file is requested relative to the host that requirejs is running on. Are there any way to control this? For example, maybe to make certain module gotten from other hosts, and for dependencies relative to that files to also be gotten from the same host.

I'd like /asset/ABCDEF to be requested from the same server as the one hosting the js file being evaluated.

**Comment by jrburke** [comment]
This is best handled by using [paths](http://requirejs.org/docs/api.html#config-paths) or [packages](http://requirejs.org/docs/api.html#packages) config, to map those path prefixes to a the start of a module ID segment.
