### ISSUE TITLE
RequireJS being throttled by new versions of Chrome

### ISSUE THREAD

**Issue by alvarorahul** [requirejs/requirejs#1635]
We've observed that the new throttling behavior in Chrome 55+ has resulted in download/parse of AMD modules using RequireJS being throttled when page is in a background tab.

**Comment by alvarorahul** [comment]
I've found that using the Q library's nextTick behavior mitigates the issue. https://github.com/kriskowal/q/blob/v1/q.js

would this be something worth porting over to RequireJS library?

**Comment by jrburke** [comment]
You might try using [alameda](https://github.com/requirejs/alameda) instead of requirejs for this issue, as alameda uses promises instead of the setTimeout mechanism that requirejs uses. No plans to change the behavior in requirejs. I would rather people moved on to alameda.
