### ISSUE TITLE
just a minor mistake on website document

### ISSUE THREAD

**Issue by 404157386** [requirejs/requirejs#1636]
Hi, I found a error...about HOW TO USE REQUIREJS WITH JQUERY, chapter 3, MODULE NAME:
"So to reiterate, you will likely get an error ifrefer to jQuery with another module name"
**ifrefer**
should be 
**if refer** 
http://www.requirejs.cn/docs/jquery.html#noconflictmap

please update

**Comment by jrburke** [comment]
I am not in control of the requirejs.cn domain, it looks like whoever maintains that domain has made a mistake in copying the site. Since I do not know who controls that site, I suggest sticking to the http://requirejs.org site for any docs or downloads.
