### ISSUE TITLE
Why define.amd = { jQuery: true};

### ISSUE THREAD

**Issue by chennas** [requirejs/requirejs#1637]
Hi Team,

Could you please explain us why in the require.js file the below define.amd is set to jquery.

    define.amd = {
        jQuery: true
    };

I could not understand why it is set as true the above lines of code by default, when I download the [require.js](http://requirejs.org/docs/download.html#requirejs) file from the official website.

Thanks in advance.

**Comment by jrburke** [comment]
Answered here https://github.com/amdjs/amdjs-api/issues/31
