### ISSUE TITLE
can I pass an array variable as dependency in require-config file.

### ISSUE THREAD

**Issue by agarwalvinit** [requirejs/requirejs#1641]
please see the below code as an example:-
`var requireArr = ['jquery', 'a', 'b', 'c'];

require(requireArr, function($, a, b, c) {
//code goes here...
});`

**Comment by jrburke** [comment]
The optimizer works by statically analyzing the code for requirejs/define calls, it does not run the file, so it will not work with specifying the array outside of the require() call.

**Comment by ScottFreeCode** [comment]
Now there's something I would not have known...

Pretty sure it works for non-optimized/non-bundled purposes, so I'll have to go back and add tests to make sure my modules bundle OK with the optimizer!

**Comment by agarwalvinit** [comment]
Ok I have a query regarding require optimizer, I want to create a single out file which will have all the js used in particular page which I am creating through grunt task and my code look like this: 
gruntFile.js
`var jsHash = {
  homePage: ['a.js', 'b.js', 'c.js'],
  nav1: ['a.js', 'd.js', 'f.js']
}

requirejs: {
  homePage: {
      options: {
        baseUrl: '<%= project.assets %>/js/brandsite',
        mainConfigFile: '<%= project.assets %>/js/brandsite/require-config.js',
        include: jsHash.homePage,
        out: '<%= project.app %>/static/main-build.js',
        optimize: 'none', //'uglify'||'none' for Prod and Dev
        fileExclusionRegExp: /^(r|require-config|build)\.js$/,
        optimizeCss: 'standard',
        removeCombined: true
      }
  },
  nav1: {
      options: {
        baseUrl: '<%= project.assets %>/js/brandsite',
        mainConfigFile: '<%= project.assets %>/js/brandsite/require-config.js',
        include: jsHash.nav1,
        out: '<%= project.app %>/static/main1-build.js',
        optimize: 'none', //'uglify'||'none' for Prod and Dev
        fileExclusionRegExp: /^(r|require-config|build)\.js$/,
        optimizeCss: 'standard',
        removeCombined: true
      }
  }
},`

my require-config.js looks like: 
`require.config({
  baseUrl: '/static/assets/js/brandsite/',
  paths: {
    bootstrap: '../../../bower_components/bootstrap/dist/js/bootstrap.min',
    bxSlider: '../../../bower_components/bxSlider/dist/jquery.bxslider.min',
    jquery: '../../../bower_components/jquery/jquery.min',
    modernizr: '../../../bower_components/modernizr/modernizr',
    requirejs: '../../../bower_components/requirejs/require',
    sticky: '../../../bower_components/sticky/jquery.sticky',
    appear: '../../../bower_components/appear/jquery.appear',
    'jquery-ui': '../../../bower_components/jquery-ui/ui',
    twitterShare: '../common/twitter/twitter-share',
    googleShare: '../common/google/google-share',
    fbShare: '../common/fb/fb-share',
    highcharts: '../../../bower_components/highcharts/highcharts',
    'jquery-validator': '../vendor/jquery-validator',
    'jquery.cookie': '../../../bower_components/jquery.cookie/jquery.cookie',
    commonConfig: 'common-config'
  },
  packages: [

  ],
  shim: {
    'jquery-ui': {
      deps: [
        'jquery'
      ]
    },
    bootstrap: {
      deps: [
        'jquery'
      ]
    },
    appear: {
      deps: [
        'jquery'
      ]
    }
  }
});


require(['jquery', 'commonConfig'], function($, commonConfig) {
//some code
});
`

So Now when I am using below configurations then it works file by creating new require-config.js but it has all the js inside it which is very large in size for me and I want to do it through out config:

gruntFile.js(require optimizer config):
`    requirejs: {
      compile: {
        options: {
          appDir: '<%= project.assets %>/js',
          baseUrl: './brandsite',
          dir: '<%= project.app %>/static/bundle/assets/js',
          modules: [
              {name: 'require-config'}
          ],
          optimize: 'uglify', //'uglify'||'none' for Prod and Dev
          paths: {
            bootstrap: '../../../bower_components/bootstrap/dist/js/bootstrap.min',
            bxSlider: '../../../bower_components/bxSlider/dist/jquery.bxslider.min',
            jquery: '../../../bower_components/jquery/jquery.min',
            modernizr: '../../../bower_components/modernizr/modernizr',
            requirejs: '../../../bower_components/requirejs/require',
            sticky: '../../../bower_components/sticky/jquery.sticky',
            appear: '../../../bower_components/appear/jquery.appear',
            'jquery-ui': '../../../bower_components/jquery-ui/ui',
            twitterShare: '../common/twitter/twitter-share',
            googleShare: '../common/google/google-share',
            fbShare: '../common/fb/fb-share',
            highcharts: '../../../bower_components/highcharts/highcharts',
            'jquery-validator': '../vendor/jquery-validator',
            'jquery.cookie': '../../../bower_components/jquery.cookie/jquery.cookie',
            commonConfig: 'common-config'
          },
          shim: {
              'jquery-ui': {
                deps: [
                  'jquery'
                ]
              },
              bootstrap: {
                deps: [
                  'jquery'
                ]
              },
              appear: {
                deps: [
                  'jquery'
                ]
              }
          },
          fileExclusionRegExp: /^(r|build)\.js$/,
          optimizeCss: 'standard',
          removeCombined: true
        }
      }
    },`

require-config.js:
`require.config({
  baseUrl: '/static/assets/js/brandsite/',
  paths: {
    bootstrap: '../../../bower_components/bootstrap/dist/js/bootstrap.min',
    bxSlider: '../../../bower_components/bxSlider/dist/jquery.bxslider.min',
    jquery: '../../../bower_components/jquery/jquery.min',
    modernizr: '../../../bower_components/modernizr/modernizr',
    requirejs: '../../../bower_components/requirejs/require',
    sticky: '../../../bower_components/sticky/jquery.sticky',
    appear: '../../../bower_components/appear/jquery.appear',
    'jquery-ui': '../../../bower_components/jquery-ui/ui',
    twitterShare: '../common/twitter/twitter-share',
    googleShare: '../common/google/google-share',
    fbShare: '../common/fb/fb-share',
    highcharts: '../../../bower_components/highcharts/highcharts',
    'jquery-validator': '../vendor/jquery-validator',
    'jquery.cookie': '../../../bower_components/jquery.cookie/jquery.cookie',
    commonConfig: 'common-config'
  },
  packages: [

  ],
  shim: {
    'jquery-ui': {
      deps: [
        'jquery'
      ]
    },
    bootstrap: {
      deps: [
        'jquery'
      ]
    },
    appear: {
      deps: [
        'jquery'
      ]
    }
  }
});


require(['jquery', 'evercookie', 'commonConfig',
	'a', 'b', 'c', 'd', 'f'], function($, evercookie, commonConfig) {
  'use strict';

});
`

Can you please tell me where am I wrong or what should I do for the first one to work. Thanks!
