### ISSUE TITLE
obsolete "licenses" in package.json

### ISSUE THREAD

**Issue by martinpitt** [requirejs/requirejs#1645]
https://github.com/bower/spec/blob/master/json.md documents the "license" field as "SPDX license identifier or path/url to a license", but the current value `new BSD, and MIT` is neither. This breaks machine parseability. Can you please change this to just "MIT"?

**Comment by martinpitt** [comment]
As bower has been deprecated, let's repurpose this for the npm `package.json`. It currently has
```json
  "licenses": [
    {
      "type": "BSD",
      "url": "https://github.com/jrburke/r.js/blob/master/LICENSE"
    },
    {
      "type": "MIT",
      "url": "https://github.com/jrburke/r.js/blob/master/LICENSE"
    }
  ],
```
but this syntax is [deprecated](https://docs.npmjs.com/files/package.json#license). Please move to `license: "(MIT OR BSD)"`.

**Comment by jrburke** [comment]
I am not sure where that licenses section is showing up. It does not seem to be in the current version of package.json in these locations:

* https://github.com/requirejs/requirejs/blob/master/package.json
* https://github.com/requirejs/requirejs-npm/blob/master/requirejs/package.json

I'm thinking this may be a reference to an older requirejs install, so closing for now, but if there is more info on where this is showing up, add it here and we can reopen as needed.

**Comment by martinpitt** [comment]
Indeed, sorry for the noise!
