### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by erhanyasar** [requirejs/requirejs#1648]
Even if I `npm install` `require`, `requirejs`, and `require.js` with my local project, I'm getting `Uncaught ReferenceError: require is not defined`. I tried the same with **browserify** and **webpack** either but not solved yet. Besides [require/issue#12](https://github.com/marcuswestin/require/issues/12) and the  [Stackoverflow](http://stackoverflow.com/questions/42791660/consequently-uncaught-referenceerror-require-is-not-defined) then I tried as a script of `require.js` and now producing the error below

<img width="687" alt="ekran resmi 2017-03-15 16 11 39" src="https://cloud.githubusercontent.com/assets/11460444/23949900/cb0e9396-0991-11e7-9a0d-8dc388ed4ac7.png">

I either tried the ways described under the link [notloaded](http://requirejs.org/docs/errors.html#notloaded) like using define or others, but none of them works.

**Comment by erhanyasar** [comment]
I'm closing the issue since the same reasons listed [this GitHub issue](https://github.com/marcuswestin/require/issues/12) and will share an answer there whenever I got an answer.

**Comment by pitronalldak** [comment]
Have the same problem

**Comment by erhanyasar** [comment]
Would you please share if you have find out any work around @pitronalldak

**Comment by erhanyasar** [comment]
Actually this is my bad or anyone's that doesn't having any knowledge of how `require`, `browsers` and `node.js` works. If the `require` is the problem within the `browser`, then simply **browserify** it. My concern was to make other `async` node.js functions besides require in the browser yet, I learned that's impossible and find a way to work around as developing node.js itself server-side with it's super easy framework [express.js](http://expressjs.com) (watch the tutorials!).

**Comment by prasadddhole** [comment]
I am also getting the same error. I also tried the **npm install requirejs** and also included global file reuire.js. But error not successful in removing the error. The code in which I am getting the error is below -
`var http = require('http');`
