### ISSUE TITLE
Bundling and minification on the fly

### ISSUE THREAD

**Issue by fatagun** [requirejs/requirejs#1650]
For the love of God or whatever you believe in. I need help. Pleaze show me some codez..

We have a web app that is composed of widgets or components that are injected into the page from a CMS. Each widget or component contains the required JS file for that one to work properly.

ie: Login widget requires login.js

Our homepage consists of 5 widgets and they cause 5 different HTTP requests to their specific JS files.

What I want to know is if I can bundle and if possible minify on the fly? or through some compilation process?

How can I bundle the required JS files? per page or per app or better on demand?

My config is something like following:

   ```
 var requireConfig = {
    	
        config: {
            'text': {
        		useXhr: function (url, protocol, hostname, port) {
        			return true;
        		}
        	}
        },
    	paths : {
    		
    	    'widgets/ui-payment':'widgets/ui-payment',
    	    'widgets/ui-money':'widgets/ui-money',
    	    'widgets/ui-isodate':'widgets/ui-isodate',
    	    'widgets/ui-date-formats':'widgets/ui-date-formats',
    	    'widgets/ui-name':'widgets/ui-name',
    	    'widgets/ui-sociallinks':'widgets/ui-sociallinks',
    	    'widgets/ui-timerangepicker':'widgets/ui-timerangepicker'
    	},
    	waitSeconds: 50,
    	shim : {
            'underscore': {
                exports: '_'
            },
    		'bootstrap' : {
    			deps : ['jquery','jquery.ui','jquery.migrate','jquery.tagsinput' ,'modernizr','sly','jquery.wholly','animate']
    		},
    		'jquery.alphanum' : {
    			deps : ['jquery' ]
    		},'jquery.mask' : {
    			deps : ['jquery' ]
    		}
    	}
    };
    require.config(requireConfig);
    
    require(['base64.min']);



```

**Comment by JasperTey** [comment]
Have you had a chance to read through http://requirejs.org/docs/optimization.html? 

In short, **r.js** is the tool (comes with requirejs) that allows you to minify and bundle your dependencies.
