### ISSUE TITLE
documentation for integrating require.js with QUnit testing framework is confusing

### ISSUE THREAD

**Issue by knbknb** [requirejs/requirejs#1672]
I found a confusing passage in the documentation. The webpage https://github.com/requirejs/requirejs/wiki/Test-frameworks says about testing framework "QUnit":

> you can get [QUnit] to work by including it in a script tag before require.js, 

but the code snippet following immediately says the exact opposite: 

	<script data-main="main" type="text/javascript" src="libs/require.js"></script>
	<script src="libs/qunit-git.js"></script>

I'll attach a screenshot , just to document what the text looked like in May 2017. It is likely that the text ano/or the code get changed sometime after this issue report. 

![selection_226](https://cloud.githubusercontent.com/assets/603200/26354179/d7e5196a-3fc3-11e7-9530-107abce2d1c9.png)

**Comment by Krinkle** [comment]
Duplicate of https://github.com/requirejs/requirejs/issues/1701. Ref https://github.com/requirejs/requirejs/wiki/Test-frameworks/_history.

Fixed at https://github.com/requirejs/requirejs/wiki/Test-frameworks.

**Comment by knbknb** [comment]
Guess this issue was a duplicate of a younger one though). Closing my own issue.

**Comment by Krinkle** [comment]
I've updated <https://qunitjs.com/api/config/autostart/#loading-with-requirejs> to include an example as well, for what it's worth :)
