### ISSUE TITLE
How can we handle the 302 status code  returned by Server when the session is timeout.

### ISSUE THREAD

**Issue by shirleyR** [requirejs/requirejs#1684]
Can it be configured to catch **302 status** or can  **be seen by requireJs** ?

How can we go into **onError** function 

Problem is similar to  [stackoverflow](https://stackoverflow.com/questions/38785581/handle-302-status-code-upon-html-js-request-to-server/38787995)

**Comment by shirleyR** [comment]
HTTP Response
```
Remote Address:
Request URL:http://js.arcgis.com/3.8/js/esri/map.js
Request Method:GET
Status Code:302 Found

Response  failed to load response data
```

when we use proxy network , we get the 302 Status 

`require(["esri/map"],function(){
// A 
}, function(){
// B
})`

**expectation is B  but go into A**

**Comment by jrburke** [comment]
A [302 status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) indicates a temporary redirection and the browser should automatically follow to the new location in the Location header. So requirejs does not have visibility into that, it just will know if some script is loaded or if it fails.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by shirleyR** [comment]
Hi , requirejs does not have visibility into 302 status but  it should know if some script is loaded or if it fails. In my case,  it seems that requirejs loaded script but module esriMap is still undefine. I'm confused.   Maybe it is esri load problem.

`require(["esri/map"], function(esriMap){
    // code goes here
   // but esriMap  is undefine 
 })`
