### ISSUE TITLE
Load timeout when working with slow connection

### ISSUE THREAD

**Issue by sebRomeo** [requirejs/requirejs#1693]
Hi I randomly get 
`Error: Load timeout for modules: ...blabla`
errors when I reload the page and this get worst as my connection get slower...

However is there a way to change this timeout to put it a bit larger please ?

**Comment by jrburke** [comment]
The [waitSeconds config](http://requirejs.org/docs/api.html#config-waitSeconds) can be used to control or even disable the load timeout.

Closing as a discussion issue.

**Comment by SivanKarthick** [comment]
Hi,
I'm also getting the same issue slow network connection, but i'm using require js and OCLazyLoad, my modules are imported via OCLazyLoad concept.

Please help anyone

PFB Screenshots
Error in Console
![image](https://user-images.githubusercontent.com/25924001/46715691-cce05680-cc7e-11e8-88ee-c01b50e322c3.png)

Declaring
![image](https://user-images.githubusercontent.com/25924001/46715741-f13c3300-cc7e-11e8-9416-c20334dd88e1.png)

Importing
![image](https://user-images.githubusercontent.com/25924001/46715756-fd27f500-cc7e-11e8-9855-a330932aa7bb.png)
