### ISSUE TITLE
Behavior of calling global toUrl method of global require

### ISSUE THREAD

**Issue by jslegers** [requirejs/requirejs#1696]
I'm using the following code to create relative URLs :

````js
define([], function() {

  var root;

  function toUrl(path) {
    return root + path;
  }

  if(require && require.toUrl) {
    root = require.toUrl('.');
  } else {
    root = window.location.origin + '/';
  }

  return {
    toUrl: toUrl
  };
});
````

It uses `require.toUrl('.')` (with the global `require` object) to determine the baseUrl of my app.

Is it safe to use `require.toUrl` this way? Is this behavior stable? Is it documented somewhere? And if the answer is "no" to any of these questions, can you suggest a better alternative?

I noticed people on StackOverflow mentioning this technique, but I can't find any official documentation for this!

**Comment by jrburke** [comment]
[The only official docs for it are here](http://requirejs.org/docs/api.html#modulenotes-urls), but it does not talk about the top level `toUrl`. However, the behavior you seems reasonable given that it is the top level `toUrl`, so it is not relative to any module ID, just the baseUrl.

There are no plans to change the behavior of toUrl, so its behavior should stay consistent for the 2.x series. There are no plans for a 3.x series.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by jslegers** [comment]
I'm having another issue with `toUrl`.

See https://github.com/requirejs/requirejs/issues/515#issuecomment-486737997
