### ISSUE TITLE
[Question] deprecating a loader/normalizing module names in a large project

### ISSUE THREAD

**Issue by DanDeMicco** [requirejs/requirejs#1698]
Hi all,

I have a question regarding removal of loaders in a project. In our project, we used to use a loader (es6!) which is a babel loader. We decided it was more trouble than it was worth, so ended up deprecating the use of the loader in our project (es6! now points to a fake loader which simply calls onload). 

```javascript
define({
    load: function (name, req, onload, config) {
        //req has the same API as require().
        req([name], function (value) {
            onload(value);
        });
    }
});
```

We have some issues now since we are no longer recommending the use of the loader, some requires of the same module are using the loader, and some aren't (see example below with some/module), and it seems requirejs thinks these are 2 separate modules and will end up doing a network call rather than using the bundled version. It is unfortunately not possible to go through all of the repositories in our project and do a find + replace all and remove es6! from everywhere.

Is it somehow possible to configure requirejs in such a way that the modules will resolve to the same module if they use the loader or not?

for example:

```javascript
require(['some/module'])
```
and
```javascript
require(['es6!some/module'])
```

Is there some way to make the above example resolve to the same module without changing every file which uses ```some/module``` (preferrably without the loader)?

Thanks for the help! Using requirejs 2.3.2

**Comment by jrburke** [comment]
I would expect that if the `define()` for  `some/module` is called before the first call to `es6!some/module`, that it would not do a network call. It may require an async operation to fulfill, but should be fine if you are using a full requirejs build, and not somthing like [almond](https://github.com/requirejs/almond) to shim the loader.

While the loader will have two entries in its registry, one for `es6!some/module` and `some/module`, if the loader is just internally calling `req(['some/module'], onload)`, then both entries in the registry should be pointing to the same thing, the export of `some/module`.

If you are seeing a network call, then maybe a fuller sketch of the scenario, even a small test, might help figure out the issue.

Closing as a discussion ticket, but feel free to continue discussion here. This issue can be reopened if we find something that leads to a code change in the loader.
