### ISSUE TITLE
Bug in QUnit Harness on "Test frameworks" wiki page

### ISSUE THREAD

**Issue by abego** [requirejs/requirejs#1701]
The [QUnit section of the Test Frameworks](https://github.com/requirejs/requirejs/wiki/test-frameworks#qunit) wiki page describes how to use the QUnit testing framework together with RequireJS.

__Problem__

However the QUnit "harness" code on the wiki page does not work when using QUnit 2.4.1, resulting in an

    Uncaught Error: Mismatched anonymous define() module: function () {
      			return QUnit;
      		}

error when using the code.

__Solution__

Load the QUnit script before RequireJS.

We also need to set `QUnit.config.autostart = false;` before the page is completely loaded. Otherwise the "load" listener of QUnit may execute and read the not yet overwritten `autostart` property. That would make QUnit do the autostart.

Therefore put the `QUnit.config.autostart = false;` before the `window.addEventListener ...` line, outside the event listener.

Here the modified script:

    ...
    <script src="libs/qunit-git.js"></script>
    <script data-main="main" type="text/javascript" src="libs/require.js"></script>
    <script type="text/javascript">
    	QUnit.config.autostart = false; // make sure QUnit does not start tests automatically
    	window.addEventListener("load", function onLoad() {

    		// Without this setTimeout, the specs don't always get execute in webKit browsers
      		setTimeout(function () {
    			//load tests using require
    			require(['firstUse/example_test'], function (one) {
    				//now trigger them.
    				QUnit.start();
    			});
    			
    		}, 10);
    		window.removeEventListener("load", onLoad, true);
    	}, true);
    </script>
    ...

**Comment by jrburke** [comment]
Thanks for pointing this out, it does seem like the wiki page was incorrect. The wiki page is updated.
