### ISSUE TITLE
Documentation Lacks Technical Efficacy

### ISSUE THREAD

**Issue by hypersoft** [requirejs/requirejs#1704]
Please document your interfaces from the top to the bottom. Code samples are not documentation, but comments.

I am trying to add your project to my project, but your reasoning about what constitutes adequated documentation does not prove to be sufficient.

A expert software coder/engineer/architect requires:

A complete Object listing. for each object: a complete function listing, with all applicable parameters, and possible return values; additionaly a complete property listing detailing the applicable values and their effects. For every function, function parameter, function return value, and property there must be a complete documentation.

THEN you provide code samples, as to how you believe the user would LIKE to use your product.

please visit: [Project Krypton: Issues: Support Script/Library Loading](https://www.github.com/hypersoft/Krypton/issues/6) for complete details and analysis as to how we got here today.

I am looking forward to working with your project. Hopefully this will be a possiblity; however that will not be likely with the current state of your documentation as presented at your website.

Although you have not asked for it, I am giving you a Technical "School Grade" of D for your documentation, which is only 1 grade above trying. I would like to see an A+.

Thank you.

**Comment by hypersoft** [comment]
You may also wish to download and install project Krypton, so that you may see a working example of what an A+ in technical efficacy looks like in terms of user help by executing `krypton --help' to get started.

**Comment by hypersoft** [comment]
One more thing, I am not sure if this is "the way it is" but please remove the js extension stripping from your code samples. It creates a very confusing situation, and you don't know what file extension the user would like to supply, so make the library file extension ignorant, as in: does not matter, but IS required. I may wish to specify .jsi for interfaces, .jsc for classes, .jsm for modules, so on and so forth. The extension of a file is very important. The reason extensions were created was to provide a visual cue as to what you are looking at, and by making it optional/stripped out, you have destroyed the very principle of its inception.

**Comment by jrburke** [comment]
This project is obviously not a fit for your wishes or style of communication. I suggest that you do not use it as you will continue to be unhappy about it. There are no plans to change things based on your feedback.

**Comment by hypersoft** [comment]
thank you for your consideration. i wish you the best in future time.
