### ISSUE TITLE
Are PR still reviewed/accepted?

### ISSUE THREAD

**Issue by dmatteo** [requirejs/requirejs#1716]
I'm looking into making a change that allows some config to be passed in to automatically applies certain plugins matching a regexp, a-la WebPack.

Something like this (specs not finalized yet)

```
pluginLoaders: [
  {  
    test: /\.js$/,
    exclude: '/bundles/',
    plugin: 'es6',
  },
  { ... },
]
```

Is it worth it to do it for the main repo and create a PR, or is this not maintained anymore?

**Comment by jrburke** [comment]
The repo is maintained for bug fixes, but no big features planned. It sounds like this feature would be for the requirejs/r.js repo.

But note the approach to plugins is different in requirejs and r.js. Loader plugins participate at runtime in the browser and build tool and they are specified by module ID prefixes. They are not file extension/glob based.

If you needed file transforms before an AMD tracing and concat step, then amodrojs/amodro-trace is likely a better tool to use instead of r.js. amodro-trace is built to be something you can plug into some other build process just to do the AMD module tracing, with that other build process managing any transforms to get the code into AMD module format.

Closing as a discussion ticket but feel free to continue discussion here.

**Comment by dmatteo** [comment]
Hey @jrburke, nice to meet you :)

I would argue the change should go in both `requirejs/requirejs` and `requirejs/r.js`.
We use `requirejs` for loading dependencies in development and `r.js` for bundling and optimizing for production.

It is true tho that modern web browsers understands pretty much all of ES2017 and ES2018, so maybe there's not a need for transpilation on local machines anymore(?)

---

I've checked out `amodrojs/amodro-trace`, but I don't fully understand how that would help with my use case. My idea is really simple: I would analyze the extension of the file on `fetch`, and eventually call a plugin if needed.

The hack-solution I have now is this (inside both branches of `fetch`)

```js
    if (map.url && /\.js$/.test(map.url)) {
      this.map.prefix = 'jsx';
    }

    return map.prefix ? this.callPlugin() : this.load();
```

Where I would like to go, is more something like this (using ES6 for brevity)

```js

    /* Example of loaders config

    this.loaders = [
      {
        test: /\.js$/,
        use: 'jsx',
        options: {
          exclude: /bower_components/
        }
      },
      {
        test: /\.css$/,
        use: 'css',
      },
    ]

    */

    const prefix = this.loaders.find(({ test, options }) => {
      return test.test(map.url) && options && !options.exclude.test(map.url);
    });

    if (map.prefix) {
      return this.callPlugin(); // maybe this.callPlugin(map.prefix) ?
    }
    
    if (prefix) {
      return this.callPlugin(prefix.use);
    }
    
    return this.load();
```

Very curious to hear your thoughts in regard.

**Comment by dmatteo** [comment]
New current version

```js
                  const loaders = context.config.loaders;
                  const prefix = loaders.find(({ test, options }) => {
                    const testRegexp = new RegExp(test);

                    if (testRegexp.test(map.url)) {
                      return options && !options.exclude.some(path => (new RegExp(path)).test(map.url))
                    }

                    return false;
                  });

                  if (map.prefix) {
                    return this.callPlugin() // maybe this.callPlugin(map.prefix) ?
                  }

                  if (prefix) {
                    this.map.prefix = prefix.use;
                    return this.callPlugin();
                  }

                  return this.load();
```

Works great, but it's horribly slow...
I think I'll be making the change only in `r.js`, and leave the development with no transformations (or manual plugins, if needed)

**Comment by dmatteo** [comment]
This fails hard with `r.js` though, with `Error: Error: Loader plugins did not call the load callback in the build:`, on files that would otherwise work perfectly fine.

If I put in my exclude list a few directories that apparently contain offending files, I can proceed to the next error, which is a missing file, for some reason(possibly not understanding aliases).

@jrburke I'm pretty lost here, I'm starting to think this is the completely wrong approach. Any help would be appreciated

**Comment by jrburke** [comment]
Yeah, loader plugins are conceptually different than file extension handlers, and I purposely wanted to avoid file extension handlers. I expect it will be very hard to retrofit, and I am not very motivated to explore an approach I explicitly discarded when first working out amd loader plugins. I appreciate that is at odds with current trends in other JS build tooling, but I am fine with that.

**Comment by dmatteo** [comment]
I understand.

Well, thanks for your time :)
