### ISSUE TITLE
specifying MVC.net bundle path in requirejs config file 

### ISSUE THREAD

**Issue by sajesh1985** [requirejs/requirejs#1720]
I am using MVC.net with requirejs, is it possible to provide bundle path in requirejs config file without using the RequireJS.NET nuget package.

Requirejs config

requirejs.config({
"baseUrl": "../Scripts",
"paths": {        
    "A": "../../Views/Claim/Startup/Referral/A",
}
});
My module A folder structure is:

 Views/Claim/Startup/Referral/A -> AController.js,AModule.js and AViewModel.js
AModule.js

 define(['A/AController'], function (AController) {
 }
AController.js

 define(['A/AViewModel'], function (AViewModel) {
 }
AViewModel.js

 define(function () {

 }
Everything is working correctly but I want to specify bundled path in my requirejs config file something like this:

requirejs.config({
"baseUrl": "../Scripts",
bundles: {
    '/bundles/startup?v=2017': [
        A
        ]
}   
});
this bundle is generated using MVC.net and it refers all the module specific files

 "~/views/claim/startup/referral/A/AController.js",
 "~/views/claim/startup/referral/A/AModule.js",
 "~/views/claim/startup/referral/A/AViewModel.js"
When I am doing the above steps i am getting errors on browser console

Uncaught Error: Mismatched anonymous define() module

Please let me know how to make this work.

Thanks Sajesh

**Comment by chrisknoll** [comment]
A 'mismatched anonymous define' usually comes from loading a module by some ID but the module was embedded with a different module ID (after optimization for example).

Could you inspect your optimized file, and see if the module you are loading from your bundle has the same ModuleID that you're requesting from your require() calls?
