### ISSUE TITLE
Uncaught Error: Module name "https" has not been loaded yet for context: _. Use require([])

### ISSUE THREAD

**Issue by kev5** [requirejs/requirejs#1724]
My script '**dataverse.js**' has these lines in the beginning-

```
var https = require("https");
var parseString = require('xml2js').parseString;
```

Now, when I run my web app, I get this error in the console-

```
require.js:168 Uncaught Error: Module name "https" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:168)
    at Object.localRequire [as require] (require.js:1436)
    at requirejs (require.js:1797)
    at VM12744 dataverse.js:1
```

I'm using the following script tags in my HTML page-

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js"></script>
<script src="scripts/dataverse.js"></script>
```

I want to display the result of '**dataverse.js**' in my browser, and it uses the 'require' which is causing me the problems while running it in the browser. Note that it runs properly when run through the node.js command prompt. 

I basically have a button whose **onclick** event should run **dataverse.js** and display the result in the browser.

Please help and thank you for your time.

**Comment by kev5** [comment]
Solved!

**Comment by chrisknoll** [comment]
Please let us know your resolution. I'm assuming that you had to either wrap  your dataverse.js file in and AMD define() wrapper, or apply some sort of shim?

**Comment by kev5** [comment]
Just use browserify.

**Comment by iEuJen** [comment]
I see. I encountered this error today and finally, I found it is the reason that I used a variable as the url. 
```js
define(function () {
    let DemoPath = require.toUrl('./components/demo.js');
    const Demo = require(DemoPath);
})
```
That is fault!!! The require's effective variable must be a direct string.
```
define(function () {
    const Demo = require('otherpath/components/demo.js');
})
```
However, if I take this way, I will not be able to have a flexible url. It is so sad.
