### ISSUE TITLE
Nested define/require inside another require does not see defined module

### ISSUE THREAD

**Issue by jrburke** [requirejs/requirejs#173]
Found in a test case by @dvdotsenko in this set of tests https://github.com/dvdotsenko/AMDLoaderTests :

``` javascript
require(['a'], function (a) {
    define('b', ['c'], function (c) {});

    require(['b'], function(b) {
        //fails because loader tries to load 'b' from network
    });
});
```

**Comment by emiglobetrotting** [comment]
nice thread..

**Comment by emiglobetrotting** [comment]
I wish to get an object from the callback in require and return it as defined module, e.g.
    define(['require', 'jquery'], function (require, jquery) {
       var obj;
        require(['something/else'], function (somethingElse) {
             obj = loadedsomething;
             console.log(obj); //expected object is defined
        });
        return obj; //obj is undefined. but I want to get as defined under this scope
    });

How can I solve this problem.

**Comment by FoC-** [comment]
You should not add nested resolution for deps. Push them to top.
[More info](http://requirejs.org/docs/errors.html#notloaded)

``` js
define(['require', 'jquery', 'something/else'], function (require, jquery, somethingElse) {
    console.log(somethingElse); //expected object is defined

    somethingElse.$ = jquery; // or something else

    return somethingElse;
});
```

**Comment by emiglobetrotting** [comment]
thanks @FoC-  got it working.

**Comment by mrtuvn** [comment]
Hi @jrburke i just recognised in 2.3.6 version. Require not able to get depend as i expected if i put inside function

define(['require', 'abc', 'something/else'], function (require, abc, somethingElse) {
    //working fine here

    someVar = {
           init: function () {
               require(['package'], function(package) {
                       package not able to work
               });
          }
    }
});
