### ISSUE TITLE
HTTPS for requirejs.org

### ISSUE THREAD

**Issue by lgarron** [requirejs/requirejs#1741]
All the download links at http://requirejs.org/docs/download.html are unsecured and easy for a meddler-in-the-middle to tamper with. Chrome will also mark the whole website as "Not Secure": https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

It would be great to protect all traffic to requirejs.org, or even go further and preload HSTS.

**Comment by jrburke** [comment]
I have updated the site to run under github, so now it is served under https. Thanks for the reminder to do the change!

**Comment by lgarron** [comment]
Thanks!

Some of the download URLs and the top of https://github.com/requirejs/requirejs still list HTTP, but those can all be tackled one-at-a-time. :-)

**Comment by jrburke** [comment]
More URL updates in https://github.com/requirejs/requirejs/commit/ae1c05157834503911c490bb57a7a080a39b3c31

**Comment by kfix** [comment]
I'm not sure why but DuckDuckGo gives me a lot of search results linked to http://www.requirejs.org/<valid resource/page item>.

If I hand-correct them to requirejs.org, the URLs work.

Can the webmaster add a www. A record to the githubPages IPs and add the www to the domains file in the pages repo?
