### ISSUE TITLE
RequireJS sporadically throws exceptions when requiring jquery

### ISSUE THREAD

**Issue by matthiasburger** [requirejs/requirejs#1747]
I'm using typescript in my .net core application and I'm managing my scripts with requirejs.

So there's a button in my footer that when click it, it calls my .net core action, receives data and shows the result on the surface.

_Layout.cshtml

    <div class="fixed-bottom">
        <footer>
            <a id="debug_button" title="Show/hide debugging">
                <span class="fas fa-code"></span>
            </a>

        </footer>
    </div>

    <script src="~/lib/requirejs/require.js" data-main="/js/config"></script>

    <script>
        require(['../ts/debugarea'],
            function(debugarea) {
                debugarea.buildDebugArea(false);

                $("#debug_button").click(function() {
                    debugarea.buildDebugArea(true);
                });
            });
    </script>

the js/config.js

    require.config({
        paths: {
            jquery: "../lib/jquery/dist/jquery",
            bootstrap: "../lib/bootstrap/dist/js/bootstrap",
            backbone: "../lib/backbone/backbone",
            underscore: "../lib/underscore/underscore",
            modernizr: "../lib/modernizr/src/Modernizr",
            unobtrusiveajax: "../lib/Microsoft.jQuery.Unobtrusive.Ajax/jquery.unobtrusive-ajax.min",
            CookieMonster: "../ts/http/CookieMonster",
            debugarea: "../ts/debugarea",
            signalr: "../lib/signalr/dist/browser/signalr"
        },
        shim: {
            backbone: ["jquery", "underscore"],
            bootstrap: ["jquery"],
            Modernizr: {
                exports: 'Modernizr',
            },
            unobtrusiveajax: ["jquery"],
            debugarea:['jquery']
        }
    });

and the debugarea.ts

    import * as $ from "jquery";

    console.log("debugarea");
    console.log($);
    
    export function buildDebugArea(switchCookie): void {
        let currentCookieValue: string = CookieMonster.CookieMonster.getCookie('debugarea');

        if (switchCookie) {
            if (currentCookieValue === "")
                CookieMonster.CookieMonster.setCookie('debugarea', "true", 1);
            else
                return clearDebugArea();
        } else if (currentCookieValue === "")
            return clearDebugArea();

        $('#debuginfo').append($('<div id="cookieinfo"></div>'));

        getCookies();
        let debugbuttonIcon: JQuery<HTMLElement> = $('#debug_button > span');
        if (debugbuttonIcon.length == 0) return;

        debugbuttonIcon.addClass("bg-dark text-white");
    }

90% of it works and my console output from debugarea.ts is

    debugarea.ts:3 debugarea
    debugarea.ts:4 ƒ ( selector, context ) {

            // The jQuery object is actually just the init constructor 'enhanced'
            // Need init if jQuery is called (just allow error to be thrown if not included)
            return new jQuery…
            
sporadically, just when reloading the browser-tab, I receive these errors here:
            
    require.js:1961 GET http://localhost:58006/js/jquery.js 404 (Not Found)
    require.js:168 Uncaught Error: Script error for "jquery", needed by: ../ts/debugarea
    http://requirejs.org/docs/errors.html#scripterror
        at makeError (require.js:168)
        at HTMLScriptElement.onScriptError (require.js:1738)
        
when reloading next time, it mostly works again.
Any idea what is going wrong here? Did I miss something?

I'm using jQuery 3.1.1 and RequireJS 2.3.5

**Comment by chrisknoll** [comment]
Is there a difference between when jquery loads without a 404 vs. when it does not?  Take a look at your console and when it works, find the network request for jquery.js.  Make a note and then try to click around to see if you can get the 404...(the 404 looks like it tried to pull jquery direclty from /js/jquery).

What could be happening is that in one click path, the 'root context' of the page is properly specified so that you find the jquery.js file in some subfolder, but when going through a different click path, the jquery asset is requested from a different root context.

**Comment by matthiasburger** [comment]
not sure.. requirejs searches in the wrong path for jquery. in the exception it searches for "/js/jquery.js" but it's in "/lib/jquery/dist/jquery.js"

I guess, it searches in that path because my config.js is in /js directory. when i then `import * as $ from "jquery";` I guess it tries to import from /js/jquery.js. Doesn't it?

So after clicking around a bit, most time when ctrl+f5 it throws that exception. when just f5 then, it mostly works.

**Comment by chrisknoll** [comment]
sounds like a race condition related to when your require.js configuration is loading, or if you're refreshing a page that's at the root vs. a page that's in a sub directory (I can't quite tell but you are not doing a single page app, right? as you click around you're loading different pages at different paths?)

If your config isn't loaded, and you do a ```require(['jquery'], function($) {...}```, the root path it will look for is the path the main .html page was loaded (or javascript file was loaded).  You're saying that your jquery module is in ```/lib/jquery/dist/jquery.js```, so to me that really points to that your require.config() is not set and there is no ```path``` configuration that points to ```lib/jquery/dist/jquery``` (note, no .js when you specify the path).

I don't know if you can set a breakpoint in your app and integgogate the current requirejs config() value to see if somehow it is just not being set.  But if it is async loaded (ie: you load a configuration settings asynchronously from loading your main entry module) the one thread that runs your app may be running 'configuration-less' which leads to your module resolve issues.

**Comment by matthiasburger** [comment]
someone said, I need to use: 
   shim: {
        ...
        debugarea: {
             'deps': ['jquery']
        }
    }

instead of :
    shim: {
        ...
            debugarea:['jquery']
    }

I did it and now it seems to work...
makes this a difference? I thought, the second one was also specifying the deps?

**Comment by ddziaduch** [comment]
This topic is already covered in the manual: https://requirejs.org/docs/api.html#data-main

RTM please 😃

**Comment by matthiasburger** [comment]
@ddziaduch my bad... :laughing: didn't read the manual. Just wanted to see this working. Thanks :rofl:
