### ISSUE TITLE
Download page throws a 404 for 2.3.6 minified...

### ISSUE THREAD

**Issue by njt1982** [requirejs/requirejs#1748]
The download page links to this:

https://requirejs.org/docs/release/2.3.6/minified/require.js

For me, this is throwing a 404...

**Comment by ddziaduch** [comment]
Same issue here

**Comment by jrburke** [comment]
Sorry about that, I missed one of the outputs. I just copied it over to the website:

https://requirejs.org/docs/release/2.3.6/minified/require.js
