### ISSUE TITLE
how to rename REQUIRE/DEFINE/REQUIREJS global constants

### ISSUE THREAD

**Issue by enforceway** [requirejs/requirejs#1767]
I'm using feature https://requirejs.org/docs/faq-advanced.html. Based on the file structure from the requirejs optimization(https://requirejs.org/docs/optimization.html). I have applied the feature of renaming require/define/requirejs with constant 'foo' and got the uglyfied and combined js file. But I have a confusing problem, which is that if I should literally write down all the dependencies for main.js to 'modules/include' settings for build.js.
content of build.js is as below:
```
({
    appDir: './src',
    baseUrl: ".",
    // mainConfigFile: './scripts/main.js',
    // name: "scripts/main",
    dir: './build',
    //Put in a mapping so that 'requireLib' in the
    //modules section below will refer to the require.js
    //contents.
    paths: {
        requireLib: 'scripts/require'
    },
    //Indicates the namespace to use for require/requirejs/define.
    namespace: "foo",
    modules: [{
        name: "foo",
        include: ["requireLib", 'scripts/one', 'scripts/two', 'scripts/three', "scripts/main"],
        //True tells the optimizer it is OK to create
        //a new file foo.js. Normally the optimizer
        //wants foo.js to exist in the source directory.
        create: true
    }]
})
```

I could build a uglified and combined js file successfully with the above build.js setting. But I supposed 
 we could trace dependency for main.js without literally setting it to the 'module/include' part in 'build.js' file. I remove  the dependencies for main.js from 'module/include' part and they are gone in uglified and combined js file. What am I supposed to do if I don't want to literally write down dependencies of main.js in 'build.js' and get them included in the uglified and combined js file?

**Comment by ddziaduch** [comment]
Hi @enforceway.

You can use node and it's file system to build an `include` array 🙂
