### ISSUE TITLE
React component AMD bundling with Webpack for Require.js

### ISSUE THREAD

**Issue by hegdeashwin** [requirejs/requirejs#1774]
Due to some reason, we want to load React component on Backbone view (with Require.js). This React component is being bundled using Webpack 4.x.

We have enable AMD/UMD mode during bundling in Webpack config.

```
...
...
module.exports = {
  entry: {
    componentName: ['./components/componentName/index.js']
  },
  amd: {
    componentName: true
  },

  output: {
    path: path.resolve(__dirname, './componentName'),
    filename: '[name].js',
    libraryTarget: 'umd',
    library: 'componentName',
    umdNamedDefine: true
  },

  externals: {
    'react': 'react',
    'react-dom': 'react-dom',
    'react-dom-server': 'react-dom-server'
  },
  ...
```

Now, we are trying to use bundled React component in Backbone+Require.js app where we are loading React and ReactDOM (UMD enabled) as below

```
define([
  'jquery',
  'underscore',
  'backbone',
  'react',
  'react-dom',
  'componentName'
], function($, _, Backbone, React, ReactDOM, componentName) {

   ...

   render: function() {
      console.log(React, ReactDOM, componentName)
   }

   ...
});
```

Here componentName always comes as undefined whereas React and ReactDOM are loading correctly. Can anyone help to understand am I missing something here?

**Comment by chrisknoll** [comment]
Looking at the non-minified bundle, can you see in the code where the react component ('componentName') is included?  I'm not familiar with webpak bundle options here (other than the UMD enabled will create the UMD preamble in the output) , but when a dependency returns null, it could mean that the dependent module didn't actually return the module value (however, you may be using ES6 and then compiling down, so those ```export``` statements should result in the exported module result.  

Only way to know is to see how Webpack injected the 'componentName' script into the otuput and see how it is returned (and set breakpoints).

**Comment by ddziaduch** [comment]
Not sure how the Webpack works. Can you please check whether bundled component does use `define()`?

**Comment by hegdeashwin** [comment]
Closing the Issue. It got resolved - the issue the React component which I was exporting. Thank for the help. And Yes the bundle contains `define()` ... and I was also able to use React's both functional and class component into dust/handlebars templating on require.js stack
