### ISSUE TITLE
optimizer: coffeescript build profile and trailing semi-colon

### ISSUE THREAD

**Issue by mikeknoop** [requirejs/requirejs#178]
This might actually be an issue elsewhere in the tool-chain but I thought I'd check here first.

According to the requirejs optimizer docs, a build profile looks like

```
({
    appDir: "../",
    baseUrl: "scripts",
    dir: "../../appdirectory-build",
    modules: [
        {
            name: "main"
        }
    ]
})
```

Writing that in CoffeeScript (1.2.0) might look simply like

```
appDir: "../",
baseUrl: "scripts",
dir: "../../appdirectory-build",
modules: [
    {
        name: "main"
    }
]
```

Which compiles to (notice trailing semicolon):

```
({
    appDir: "../",
    baseUrl: "scripts",
    dir: "../../appdirectory-build",
    modules: [
        {
            name: "main"
        }
    ]
});
```

And sure enough, I receive an error during optimization.
"Error: Build file /var/www/snapier/media/js/src/app.build.js is malformed: SyntaxError: Unexpected token ;"

Any insight what's going on here? Thanks!

**Comment by jafow** [comment]
Thought I would add onto this FWIW. Got the same SyntaxError described above (`Unexpected token: ;`) when using optimizer on a plain JS build config in **Nodejs v6.5**. Removing the semicolon at the end of the file fixes the error. 

However, running the same build config in **Nodejs v4.5** builds with no error, even when I _don't_ remove the final semicolon.

**Comment by jrburke** [comment]
@jafow https://github.com/requirejs/r.js/issues/767 should have addressed the issue with a trailing ; in the build config. If you are still seeing this, would you mind putting up a small sample project that I could try? I would not expect a difference between 4.5 and 6.5.

Going to close this as the above referenced issue should address the original issue, but if you have an example where it still breaks, then comment here and I can open a new bug to track any fix for that.

**Comment by jafow** [comment]
Thanks @jrburke it's probably fine closing. Here's a demo to try running with Node v4.5 and 6.5. [create-template-app](https://github.com/jafow/create-template)

I just added a new build file with a trailing ;, and do `r.js -o <build_file_with_semi>` and get the error.  Switching to Node v4.5 builds without error.

**Comment by jrburke** [comment]
@jafow thanks for the test case. I did the following with node 6.5.0 on OS X, and it seemed to work for me:

```
[~/git/temp/create-template(master)]$ git clone --recursive git@github.com:jafow/create-template.git
[~/git/temp/create-template(master)]$ cd create-template/
[~/git/temp/create-template(master)]$ node -v
v6.5.0
[~/git/temp/create-template(master)]$ node tools/r.js -o tools/build_with_semis.js 

Tracing dependencies for: app
Uglify file: /Users/x/git/temp/create-template/www-built/app/main.js
Uglify file: /Users/x/git/temp/create-template/www-built/app/messages.js
Uglify file: /Users/x/git/temp/create-template/www-built/app.js
Uglify file: /Users/x/git/temp/create-template/www-built/lib/print.js
Uglify file: /Users/x/git/temp/create-template/www-built/lib/require.js

app.js
----------------
app/messages.js
lib/print.js
app/main.js
app.js
```

Maybe an issue on a different OS, or how 6.5 was installed?
