### ISSUE TITLE
requirejs.config map: Multiple files for "*"

### ISSUE THREAD

**Issue by LukeOwlclaw** [requirejs/requirejs#1784]
I'd like to map multiple files by default ("*"). The example only shows how to [map a single file](https://requirejs.org/docs/api.html#config-map):
```
requirejs.config({
    map: {
        '*': {
            'foo': 'foo1.2'
        },
    }
});
```

I'd like to have:
```
requirejs.config({
  "map": {
    "*": [
      {
        "foo": "foo1.2"
      },
      {
        "bob": "bob1.2"
      }
    ]
  }
});
```
But this does not work. What is the correct syntax?

**Comment by chrisknoll** [comment]
No, you're making the field `*` into an array.  Just add additional fields to the objec,t just like you do with paths:

```
requirejs.config({
    map: {
        '*': {
            'foo': 'foo1.2',
            'bob': 'bob1.2',

        }
    }
});
```
