### ISSUE TITLE
Support ES6 by using the harmony branch of uglifyjs

### ISSUE THREAD

**Issue by mutec** [requirejs/requirejs#1790]
It would be great if compressing/minification of ES6-JavaScript would be supported.
Since the current version of uglify-js (2) does not support this, it might be good to use the `harmony` branch-version instead.
https://github.com/mishoo/UglifyJS2/tree/harmony#uglify-es

**Comment by ddziaduch** [comment]
I think @jrburke has abandoned this project 🤔

**Comment by jrburke** [comment]
I've commented in other issues (although I appreciate that is hard to find) that I don't think it makes sense to keep bundling a minifier in r.js, and now that JS/node-based build pipelines are more advanced than when the project started, my recommendation is to set `optimize: none` in r.js config, and instead minify with the minifier of your choice in a build step process after r.js runs.
