### ISSUE TITLE
There are no start.md and api.md files in this project

### ISSUE THREAD

**Issue by Alanscut** [requirejs/requirejs#1799]
I was reading the source code of requirejs and I found that **start.md** and **api.md** files were involved in **index.html**, but I didn't find these two files in the project. I checked the committed records and I found that these two files existed in version 0.15.0, but the file names were changed to **start.html** and **api.html** in version 0.2.0, Is this historical problem?

```html
// index.html
 <p><a href="requirejs/tree/master/docs/start.md">Get started</a> then check out the <a href="requirejs/tree/master/docs/api.md">API</a>.</p>
````

**Comment by jrburke** [comment]
There is script that is run before publishing that replaces .md references with .html:
https://github.com/requirejs/requirejs/blob/master/dist/dist-site.js#L74

Closing as a discussion ticket, but feel free to continue discussion here.
