### ISSUE TITLE
Dependencies are not resolving if path config contains duplicate URLs

### ISSUE THREAD

**Issue by ankur-bambharoliya** [requirejs/requirejs#1813]
**Current Behavior:**

For config like,

```javascript
require.config({
    paths: {
        alpha: 'https://duplicate.com/duplicate/path/',
        beta: 'https://duplicate.com/duplicate/path/'
    }
});
```
if you do two requires for two different modules like,

```javascript
require(['alpha'], (alphaMode)=>{
    alphaMode.do() // this code works
});
```

```javascript
require(['beta'], (betaMode)=>{
    betaMode.do() // this doesn't  works
});
```

then one first module gets resolved.

**Expected Behavior:**

Both the modules should get resolved.

**Comment by ankur-bambharoliya** [comment]
@jrburke Can I submit a PR to fix this bug?

**Comment by jrburke** [comment]
Use map config to alias one of the module ids to the other id then use paths config for the main target module id to convert that module id to a path.

Closing as a discussion ticket, but feel free to continue discussion here.
