### ISSUE TITLE
Support to work with IndexedDB, localstorage etc.. filesystems with BrowserFS

### ISSUE THREAD

**Issue by steffanhalvorsen** [requirejs/requirejs#1819]
It would be great if this lib could require files from files stored in IndexedDB, localstorage, memory, dropbox etc..

https://github.com/jvilk/BrowserFS

**Comment by jrburke** [comment]
No plans to support this, but you could try to do this by loading the script tag for requirejs, then after it override requirejs.load to load the module source from some other source. It may take a bit of work to figure out though:
https://github.com/requirejs/requirejs/blob/master/require.js#L1885

Closing as a discussion ticket, but feel free to continue discussion here.
