### ISSUE TITLE
[Report] [ERROR] - schema.validation.error : JSON schema validation failed: : Missing required property: server

### ISSUE THREAD

**Issue by NikitaJainTR** [requirejs/requirejs#1837]
We have migrated JRS 7.1.1. to 7.9.1 and since than we are not able to load Report Dashboard. It gives below error:
[Report] [ERROR] - schema.validation.error : JSON schema validation failed: : Missing required property: server

Please help.

**Comment by jrburke** [comment]
This looks like it was filed for a different project, closing.
