### ISSUE TITLE
Typo in URL for release 2.3.7 issue link on download.html page

### ISSUE THREAD

**Issue by dpetersonx** [requirejs/requirejs#1858]
Minor: In docs/download.html (also found at https://requirejs.org/docs/download.html#2-3-7) the text "Security Vulnerability: Prototype pollution" links to `hhttps://github.com/requirejs/requirejs/issues/1854`.  There is an extra `h` in the protocol `hhttps:`.

**Comment by jrburke** [comment]
Sorry I missed this, fixed in https://github.com/requirejs/requirejs.github.io/commit/7653565234fa1edacbb3a37876e4370dcb50161c
