### ISSUE TITLE
Feature Request: Ability to configure the fetch priority for loading resources

### ISSUE THREAD

**Issue by nischithbm** [requirejs/requirejs#1861]
The current implementation does not specify/assign a fetch priority when the when RequireJS loads resources by inserting a script tag into the browser. As a result, the browser defaults to selecting the priority, which in several web applications, tends to be 'low' priority.

**Desired Behavior**: We aim to assign a 'high' priority for critical JS/CSS resources and 'low' priority for non-critical JS/CSS resources. This adjustment will allow the browser to prioritize critical resources more efficiently.

However, at present, there is no mechanism available to customize the fetch priority.

We need an ability to configure fetch priority at 2 levels
**1. global configuration**
  - this can be easier to configure since this doesn't change the require("moduleName") API
  - Essentially, we can configure it to have a default value lets say 'high', so that all resources are loaded with 'high' priority. It can be other-way around as well.

**2. configure fetch priority for specific require call**
  - this will need some discussions to ensure that right API changes are introduced. 
  - This will help us load specific non-critical resources with 'low' priority. It can be other-way around as well.

## Open quesiton:
How does this inter-operate with other AMD loaders (eg: Dojo loader), how can we create a spec/API that can be implemented by other AMD loaders as well?

## Code Reference:
- https://github.com/requirejs/requirejs/blob/2.3.7/require.js#L1946 Currently it doesn't add fetchpriority attribute to the script tag.

## Reference:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#fetchpriority

## Webpack
Webpack has recently added support to customize/configure fetch priotity while loading resources
- https://webpack.js.org/api/module-methods/#webpackfetchpriority
- https://webpack.js.org/configuration/module/#moduleparserjavascriptdynamicimportfetchpriority
- https://github.com/webpack/webpack/issues/16989
- https://github.com/webpack/webpack/pull/17249

**Comment by jrburke** [comment]
You can do this by overriding [requirejs.createNode](https://github.com/requirejs/requirejs/blob/945ae6b41ef81851a030d93759bd36ac75a39958/require.js#L1876C9-L1876C19). The override can be done similar to how [this example overrides requirejs.load](https://github.com/requirejs/requirejs/wiki/Fine-grained-URL-control).

No plans to make changes to the code to support setting fetch priority in configuration. This project is not implementing new features.
