### ISSUE TITLE
text! plugin works offline only in Firefox and Safari

### ISSUE THREAD

**Issue by AgostinoSturaro** [requirejs/requirejs#190]
I need to load some external templates and have them work offline.

The text! plugin works offline only in Firefox and Safari.

This is my code

``` html
<!-- index.html -->
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">    
    <head>
        <title>Example Application</title>
        <script data-main="main" src="require.js"></script>
    </head>
    <body>
        <p>Example Application</p>
    </body>
</html>
```

``` javascript
// main.js
require.config({
    paths: {
        text: 'text'
    }
});

require(["text!textFile.txt"], function(t) {
    alert(t);
    console.log("asd"+t);
});
```

textFile.txt has just  word inside it

Firefox 10 and Safari correctly display the alert with the content of the file.

Chrome 17 and Opera 11.61 display an empty alert.

Internet Explorer 9 displays a prompt asking to allow ActiveX content,
but when given confirm doesn't show any alert at all.
There's an error in the Console, here it is, translated:

SCRIPT5: Access denied.
text.js, Line 27 Character 17

**Comment by danialwestmorland** [comment]
I know this is an old thread, but thought I would add what I'm finding. I have created a Cordova mobile app that worked great in VS2015, however VS2017 version of Cordova blocks ActiveX requests.
