### ISSUE TITLE
Config Paths auto-appending .js

### ISSUE THREAD

**Issue by quantumlord42** [requirejs/requirejs#208]
Hi,
I am trying to learn require.js and see if it will be useful for integrating into the CMS that I use.

However, because of the fact that the config paths object auto-append ".js" to the path, it makes require.js impossible to be used in a versatile, flexible manner regardless of if it is being used with a CMS or not.

Two example cases:
1. If there is a PHP file that compiles the list of need javascript  files to include: "/path/to/file.php".
2. If the server is configured to run most URLs through a single index.php (as the case with the CMS). ("/javascript/files/")

In both of the above cases, appending ".js" will result in a 404 not found.

Is there a way to disable to addition of ".js" to the end of the path?

**Comment by Yugloocamai** [comment]
I have the opposite problem and I can't for the life of me figure out how to get require.js to APPEND .js to all my requires.  It keeps trying to load /js/index instead of /js/index.js
