### ISSUE TITLE
Relative module path resolution fails after loading from absolute path

### ISSUE THREAD

**Issue by elima** [requirejs/requirejs#230]
When I 'require' a remote module using an absolute url (http://) path, and that module requires other modules relative to it, the resolved paths for these modules are also absolute but lack the ".js" extension thus they are not found.

Example:

```
require (["http://other.domain/remoteModule.js"], function (RemoteModule) {
   ...
});
```

And inside RemoteModule:

```
define (["./otherModule"], function (OtherModule) {
   ...
});
```

Require.js will load RemoteModule fine, but then will try to load OtherModule from the url http://other.domain/otherModule (without the extension) and fails with not-found error.

My use case is simply loading a remote module that has relative dependencies. What would be the correct way to do this?

**Comment by fdecampredon** [comment]
we use requirejs to provide a kind of 'plugin' system, and it seriously makes everything complex, @jrburke could we hope that you reconsider ? adding a 'path' is not an option for us neither.
