### ISSUE TITLE
2.0: require() callbacks called twice?

### ISSUE THREAD

**Issue by jrburke** [requirejs/requirejs#260]
Reported by @kr1zmo in the [draft thread](https://github.com/jrburke/requirejs/issues/255#issuecomment-5506875):

---

Hey programing friends,

I discovered an issue in this beta release; cannot really replicate it with an example url, so I will attempt a description.  I have a backbone collection listening for the addition of models, a function runs when these events occur. Inside the function that executes for each model added, I have a simple statement.

``` javascript
require(["view/discussionitem"], function(DiscussionItemView) {
          var discussionitem = new DiscussionItemView({model: model, dateToday: view.dateToday, dateYear: view.dateYear});

          if(parseInt(model.get('id')) >= view.collection.newid) {
            view.collection.newid = parseInt(model.get('id'));
            view.discussionContainer.append(discussionitem.el);
          }else {
            view.discussionContainer.prepend(discussionitem.el);
          }
       });
```

The require statement fires twice for each call. I noticed the issue because I have discussions that render and duplicates were appearing for the same comment.  I'm thinking the calls might so subsequent that it is executing twice. 

<h2>Reverted back, not an issue with v 1.0.8</h2>

Notes: I have verified the extra calls only reside in the require function, outside, the correct amount is called.  Tested using console.log();

Thanks. Everyone.

**Comment by deltreey** [comment]
I can confirm that this is happening.  You can see a (not simple) example of it here: http://deltreey.github.io/Dable/ on the second example (built with html table) and the 5th example (alternating styles).  Note that if you clone the code (and checkout the gh-pages branch) you can add a console.log statement in either of those callbacks and it appears twice.  It may not be the simplest example, but it doesn't require a server to confirm it (just open index.html in a browser).

**Comment by jrburke** [comment]
@deltreey there seems to be some double eval of the scripts in that page, maybe by whatever templating solution you have running that replaces the `{{{navbar}}}` stuff? If I just do a console.log() outside the require call it shows up twice, so it indicates all the scripts are just run twice in the page.

**Comment by deltreey** [comment]
nice!  Thanks.  It was because mustache was re-rendering my script tags that caused them to be called twice.  I fixed it and I withdraw my previous comment.
