### ISSUE TITLE
enforceDefine triggers error on main file

### ISSUE THREAD

**Issue by dustinboston** [requirejs/requirejs#298]
Hey James, just upgraded to Require 2.0. Really nice work. I wanted to report a bug relating to enforceDefine, here's the repro using the require-jquery sample project (also reproducible with the non-require-jquery version, loading jquery as a dep):

``` javascript
// main.js
requirejs.config({
  enforceDefine: true,
  shim: {
    'alpha': ['jquery'],
    'beta': ['jquery']
  }
});

// Change to `require` to `define` and the error will go away
require(["jquery", "alpha", "beta"], function($) {
    //the jquery.alpha.js and jquery.beta.js plugins have been loaded.
    $(function() {
        $('body').alpha().beta();
    });
});
```

**Steps** 
1. Set enforceDefine: true
2. require() some modules as normal

**Expected**
All modules loaded without errors

**Result**
All modules loaded, BUT error `No define call for main http://requirejs.org/docs/errors.html#nodefine` displayed in console

**Workaround**
Change `require` to `define`. 

I've repro'd the bug in Chrome/Firefox latest. Let me know if you need anything else or would like me to email you the files.

**Comment by restarian** [comment]
It seems like enforceDefine should exclude any config passed in with a require call.  The main file below keeps the config seperate but enforceDefine still errors.
_main.js_
`require(["require_config"], function(config) {
  require(["dom_ready"], function() {

    require(["two", "three"], function(two, three) {
      two.hi()
      three.hi()
    })

  })
})
`
