### ISSUE TITLE
r.js optimizer does not load paths defined by a require.config

### ISSUE THREAD

**Issue by brettcave** [requirejs/requirejs#308]
Given the following snippets valid for requirejs without optimization:

main.js:

```
require.config({
    paths: {
        jQuery: 'libs/jquery/jquery',
        Underscore: 'libs/underscore/underscore',
        Backbone: 'libs/backbone/backbone'
    }
});

require([
    'global',
    'order!libs/jquery/jquery-1.6.2.min',
    'order!libs/underscore/underscore-min',
    'order!libs/backbone/backbone-min'
], function(Global) {
    Global.initialize();
});
```

global.js:

```
define([
    'jQuery',
    'Underscore',
    'Backbone'
], function($, _, Backbone) {
    var initialize = function() {
        // do something;
    };
    return {
        initialize: initialize
    };
});
```

When using requirejs , this code works as expected, but when trying to run the optimizer the paths for modules are lost, and need to be declared as CLI arguments:

```
$ node ../../../node_modules/requirejs/bin/r.js -o name=main  out=main-built.js baseUrl=. 

Tracing dependencies for: main
Error: ENOENT, no such file or directory '/path/to/jQuery.js'
In module tree:
    main
      global

Error: ENOENT, no such file or directory '/path/to/jQuery.js'
In module tree:
    main
      global
    at Object.openSync (fs.js:240:18)
```

However, if I add:

```
$ node ../../../node_modules/requirejs/bin/r.js -o name=main out=main-built.js baseUrl=. paths.jQuery=libs/jquery/jquery
```

jQuery is found and the next module fails (underscore / backbone / etc). When running the optimizer, should it not load up the module paths from require.config { paths: {}} ?

**Comment by Pines-Cheng** [comment]
mainConfigFile is useful to share requirejs config.

**Comment by davidrhoderick** [comment]
I agree; I'm first time messing with require so I didn't look far enough ahead (my bad) into optimization but now I have a complex project and I just want to drop it in r.js and have it work.  That should be the default behavior IMHO.
