### ISSUE TITLE
How to get the current module's name?

### ISSUE THREAD

**Issue by kadishmal** [requirejs/requirejs#352]
Seems very simple, but I cannot get it work. How should I get the current module's name considering that I do not set any custom name?

**Comment by ORESoftware** [comment]
well,it might be useful to have a utility like this:

```javascript
define('xyz',['module'], function (module) {
  console.log(this.moduleName); //would log 'xyz'
});
```

does 'this' even have a meaning inside an AMD module? I don't even know and I should by now

I use logging for debugging to see the order of loading/execution

**Comment by ORESoftware** [comment]
in other words, it would be nice if the context for 'this' inside each module was the module itself

**Comment by ORESoftware** [comment]
I just investigated - 'this' for an AMD module is just the global (window). If you were to rewrite RequireJS it would be really cool to make 'this' in a module basically like module.exports in Node.js.

Frankly I think it's kinda stupid that both CommonJS and AMD have 'this' refer to global. If you want the global, then refer to window or global in AMD/CommonJS.

IMO 'this' in both CommonJS and AMD should refer to the current module, makes way more sense. My 2 cents, maybe it's crazy wrong, can't tell.

**Comment by ORESoftware** [comment]
```javascript
define('my_module', function(){

   console.log(this.moduleName); // logs 'my_module'

   this.exports.foo = 'foo';
   this.exports.hello = function(){}
 
});
```

I think it would be really cool if there were a RequireJS 3.0 :)

**Comment by jrburke** [comment]
The 'module' special dependency ID gives access to the ID and URL of the current module:
https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#magic
