### ISSUE TITLE
Document how to define a require-config file shared across different scripts

### ISSUE THREAD

**Issue by idflood** [requirejs/requirejs#354]
Hi,

The new version of requirejs looks really promising but I have a little issue. Previously I used the !order plugin to load a main config file which was used for the normal page, tests and other places.

For instance, the file was loaded from the boot.js file : https://github.com/idflood/next-boilerplate.js/blob/master/src/scripts/boot.js
And the config file looked like this: https://github.com/idflood/next-boilerplate.js/blob/master/src/scripts/require-config.js

Now, without the !order plugin this trick doesn't work anymore. I have some ideas about possible solutions but I can't find an elegant one. One easy solution would be to have nested require calls, but if I'm right the r.js optimizer will not really work with that.

Any idea to solve this in an elegant way?

**Comment by RinkAttendant6** [comment]
None of these configurations on the wiki page work on a site that has a [Content Security Policy of `script-src`](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#script-src_2) lacking `'unsafe-inline'`. The closest one is option 4 but that assumes all app entry points are called `main.js`.

I could make separate `config.js` files for each page but that defeats the purpose.

Any idea on how to solve this without repeating the config everywhere?

**Comment by jrburke** [comment]
@RinkAttendant6 I believe https://github.com/requirejs/example-multipage will work in that scenario.

**Comment by hagabaka** [comment]
One of the use cases for having a separate require config file is to use it in both the "main" script and a web worker script. In that case, the config file shouldn't reference anything like `document`, so this rules out a few other setups above that use custom `<script data-` attributes.

**Comment by stavinsky** [comment]
I have a question about nested require. It's looks like a very good variant, and it works good. But when I'm trying to minify such file using r.js it doesn't find any requirements. 
For example this doesn't work with r.js optimization but works in browser:
```javascript
require(['main'], function (common) {
    require(['router'], function (router) {
        router.initialize();
    });
});
```
This example works everywhere but here is the problem with async loading. Sometimes main loads after some other requirements and application get fault because it trying to load files from wrong place.
```javascript
require(['main'], function (common) {
});
require(['router'], function(router){
    router.initialize();
});
```

**Comment by tkissing** [comment]
While that might work, your "Sometimes main loads after some other requirements and application get fault" sounds like you have unexpressed dependencies in one or more modules. In other word, some of your code expects main to have run, but does not actively require it.

**Comment by cention-mujibur-rahman** [comment]
I have a question if I want to use @DimitarChristoff 's mentioned in his last point, will it be safe?
like: 
<script src="bower_components/requirejs/require.js"></script>
<script src="js/require-config.js"></script>
<script src="js/main.js"></script>

**Comment by joshperry** [comment]
Deferred scripts are executed in the order they are downloaded (and before DOMContentLoaded).

Using this technique is working great for me with a progressive enhancement strategy:
```html
<head>
    <script defer src="js/require.js"></script>
    <script defer src="js/main.js"></script>
</head>
```
