### ISSUE TITLE
versioning main.js with query strings

### ISSUE THREAD

**Issue by btmdave** [requirejs/requirejs#476]
I'm trying to add versions to our main.js to update browser cache with each release.

Doing this however doesn't work:

`<script type="text/javascript" data-main="js/main?v=1" src="js/require.js?v=1"></script>`

Is there a "requirejs" way to do this?

Thanks!

**Comment by golovatuy** [comment]
you can generate version at the end of files

require.config({
	baseUrl: "Scripts/app",
	urlArgs: "v=" + (new Date()).getTime(),
	paths : {
		jquery: "https://code.jquery.com/jquery-2.1.4.min"
	}
})
