### ISSUE TITLE
Map config duplicating alias replacement when alias, folder and script names match.

### ISSUE THREAD

**Issue by guybedford** [requirejs/requirejs#484]
Thanks for all the help so far, this is the last issue for a while I hope! These are all related to getting plugins working smoothly, I'm not just trying to find things I promise. 

If I include the map config:

``` javascript
{
  map: {
    '*': {
      'plugin': 'plugin/plugin'
    }
  }
}
```

I see a request running to '/plugin/plugin/plugin.js' in the browser for a plugin load of the form `plugin!...`. I'm not sure of the internals of the map, but a request to 'plugin' would ideally resolve to 'plugin/plugin', not running the mapping twice. I can understand though if 'plugin/plugin' would return 'plugin/plugin/plugin' under this config.

**Comment by dcleao** [comment]
Should I understand from this issue that a map configuration cannot be applied twice? I mean, for the following config:
```javascript
{
   map: {
      "*": {
         "a": "b"
         "b": "c"
      }
   }
}
```
requesting `a` yields `b`, instead of `c`?
(independently of being plugins or not)
Thanks

**Comment by jrburke** [comment]
correct, it is only done once: if a module asks for "a", it gets "b", not "c". If some other module asks for "b", it would get "c".

**Comment by dcleao** [comment]
Thanks! It would be great if you could add this information to the requirejs site; at least I couldn't find it anywhere.
