### ISSUE TITLE
Question on how requireJS handles scripts loaded statically

### ISSUE THREAD

**Issue by eclifford** [requirejs/requirejs#535]
How does RequireJS handle scripts listed as dependencies that were already loaded statically via  a script tag?

For example I create something like below. What is happening exactly? Is JQuery loaded twice? I'm noticing a lot if issues in my code with JQuery plugins due to the need to make JQuery (and several) of our plugins statically included (not all of our site is AMD). I like to better understand what is going on below and how to work around it.

``` html
<html>
  <head>
    <script src='scripts/jquery.js'></script>
    <script src='scripts/jquery.plugin.js'></script>
  </head>
  <body>
     require([''scripts/jquery"], function() {
         // jquery.plugin acts very erratically probably due to jquery loaded twice?
      });
  </body>
</html>






```

**Comment by azizhk** [comment]
This was very helpful.
Can you tell what would happen if I am loading jquery using async attribute
```<script src="scripts/jquery.js" async></script>```
Would that result in a double load?
