### ISSUE TITLE
Only minifying my own code?

### ISSUE THREAD

**Issue by jockster** [requirejs/requirejs#572]
I would like to exclude jQuery from minification to speed up builds, but included it in the concatenated file. I have the below shown directory structure in my project and tried passing `paths.jquery=empty:` when running `r.js`, but then jQuery seems to be excluded completely. What am I doing wrong?

Directory structure:

```
js
  app.build.js
  libs
    jquery.js
```

And my buildfile:

```
({
    baseUrl: ".",
    out: "myproject.min.js",
    paths: {
      jquery: "libs/jquery"
    }
})
```

**Comment by thatguynamedandy** [comment]
+1

**Comment by theseyi** [comment]
+1
