### ISSUE TITLE
QUnit tests stop running (in PhantomJS) when upgrading from 2.0.6 to 2.1.*

### ISSUE THREAD

**Issue by fabien-d** [requirejs/requirejs#618]
Without changing any behaviour in the test suite, simply updating the requirejs library from `2.0.6` to `2.1.*` prevents all my tests from running in PhantomJS. (May be linked to #554)

I've put together a simple test repo to recreate the issue at https://github.com/fabien-d/require-qunit-test.

---

![Screen Shot 2013-01-31 at 8 00 57 AM](https://f.cloud.github.com/assets/747616/114557/4d142420-6ba6-11e2-8546-8822c7676b9a.png)
## 2.0.6

![Screen Shot 2013-01-31 at 8 04 00 AM](https://f.cloud.github.com/assets/747616/114565/ee1278e0-6ba6-11e2-8e88-8bf0269a81c7.png)
## 2.1.4

![Screen Shot 2013-01-31 at 8 05 12 AM](https://f.cloud.github.com/assets/747616/114566/f24f21e2-6ba6-11e2-800c-d0062429b903.png)

**Comment by philostler** [comment]
@frederickf Do you have anything open source I can look at on how to tie everything together? I'm trying to get a similar setup working with PhantomJS + RequireJS + QUnit

**Comment by frederickf** [comment]
@philostler I don't, sorry.

**Comment by philostler** [comment]
No problem, fixed my issues in the end. Thanks anyway!

**Comment by ernsheong** [comment]
@philostler Would be great if you could share your solution for PhantomJS + RequireJS + QUnit :smiley:
