### ISSUE TITLE
Using requirejs in WordPress - wp_enqueue_scripts

### ISSUE THREAD

**Issue by gnrocks** [requirejs/requirejs#622]
Hi !

I am looking to include RequireJS in a WordPress page with the wp_enqueue_scripts function.

The problem here is that the original &lt;script ....&gt; declaration for RequireJS contains a data-main attribute that is not handled by wp_enqueue_scripts.

Is there any way to set this attribute directly through the .js file ?

The reason why i want to use wp_enqueue_scripts is because i conditionally load other scripts and this provides me with a way to control dependancy over those extra plugins.

Thank you !

**Comment by Giovanni-Mattucci** [comment]
@jrburke so glad I found this thread, fixed the same issue I had with colliding jquery inclusions.

Alternatively, another solution I had in mind also was to load jquery using enqueue scripts, running requirejs before everything, and then setting jquery with requirejs in a gruntfile like this: 
```javascript
requirejs: {
      compile: {
        options: {
          baseUrl: '/js/',
          mainConfigFile: '/config.js',
          name: 'main',
          out: '/dist/',
          paths: {
            'jquery': 'empty:'
          }
        }
      }
    }
```
You can read about it here: http://requirejs.org/docs/optimization.html#empty
Used for when you want to use a resource from a CDN, but could apply in this case with Wordpress.
