### ISSUE TITLE
Uncaught Error: Load timeout for modules

### ISSUE THREAD

**Issue by szuzul** [requirejs/requirejs#628]
When I'm using the require in backbone app I'm getting 
Uncaught Error: Load timeout for modules: appe or 
Uncaught Error: Load timeout for modules: main, appe
http://requirejs.org/docs/errors.html#timeout when I'm open ripple service .
Without ripple service application is working fine, all paths of the modules main and appe are set up correct I'm not getting 404 response from server either. Server is running localy so I'm using ripple proxy in the middle also

My request from client to local server take a 3-4 seconds, after  that the request is received, this error jumps up. Any hints ?
Regards,

**Comment by libillgithub** [comment]
I meet this question sometimes in my project just because the lan speed sometimes is slow. I'll try this method to solute my question. Regards!

**Comment by nasouhmr** [comment]
> Thanks for the tip I set waitSeconds to zero and error was gone.
> 
> Regards

thanks
