### ISSUE TITLE
Specify current working dir when using optimize in node

### ISSUE THREAD

**Issue by nonken** [requirejs/requirejs#659]
I am running into weird issues when I call optimize from a node context. Right now I have two scenarios:
1. Calling from commandline within the project I want to optimize (works great, using current working dir)
2. Calling in a server environment where the project is in a different location than the module calling optimize. This fails as paths are not correct.

Other info

I only want to optimize one file and am using

```
out: function() {}
```

I tried setting appDir in the build config (to cwd when from command-line and to tmp dir when calling in server env) but then am getting 

```
TypeError: Cannot read property 'length' of undefined
    at Function.build.makeAbsPath         (.../node_modules/requirejs/bin/r.js:22454:51)
```

which fails in line 22682

```
if (config.appDir) {
    config.dirBaseUrl = build.makeAbsPath(config.originalBaseUrl, config.dir);
}
```

Now when I set config.dir as well (this is what the code implies I think) I get:

```
Error: "appDir" is not compatible with "out". Use "dir" instead. appDir is used to copy whole projects, where "out" is used to just optimize to one file.
```

So my main question is: can I set a projects root somehow while at the same time just wanting to optimize one file, using out?

**Comment by sayyedhanif** [comment]
I have my build.js profile file as following
({  
	baseUrl: "../public/javascripts/backbone/userDashboard",  
	mainConfigFile: "../public/javascripts/backbone/userDashboard/main.js",
       

    modules: [
        {
            name: 'main'
        }
    ],
    out: "../public/javascripts/backbone/userDashboard/main-built.js",
    preserveLicenseComments: false
})

but am having the error
Error: Error: "appDir" is not compatible with "out". Use "dir" instead. appDir is used to copy whole projects, where "out" with "baseUrl" is used to just optimize to one file.
    at Function.build.createConfig (/home/hanif/SQr/pd/build/r.js:27988:19)

Can any one know where is actual mistake
