### ISSUE TITLE
Need method require.hot('some-module') analog in Node.js

### ISSUE THREAD

**Issue by wwwboy** [requirejs/requirejs#664]
Sometimes modules are generated in realtime and there is a need to load the freshest version of the module from a server.
In Node.js community such feature is realized is there any chanse to be realizesede this feature&

**Comment by pei-han** [comment]
> FWIW, I also believe that reloading applications is not sufficiently satisfactory. Modern thick clients (or "Single-page applications") may have complex state that is difficult to serialize and save and would take a non-trivial amount of time to rebuild when initializing the application.
> 
> While these are not common, there is a general expectation that they will be. Require.js would benefit from supporting long life cycles a little bit better.

Is there any solution so far?Thank a lot.
