### ISSUE TITLE
Setting removeCombined to true causes require to delete all files configured using paths.

### ISSUE THREAD

**Issue by atrniv** [requirejs/requirejs#755]
Require JS seems to delete all 3rd party library files which I have configured in my paths options when I set the removeCombined option to true. Is this intended behaviour ? 
I need some way to output only the optimized files to a output folder without any of the original source files. What's the best way to do this ?

**Comment by toddb** [comment]
Sorry also to comment on a closed issue. I am having a problem on 2.1.16. I have a css file (which is out of the directory structure) being deleted after I turn on the `removeCombined` option.

It works first time and then on second run (because it is deleted), it warns me:
```
dist/css/site.css
  Cannot inline css import, skipping: ../../bower_components/bootstrap/dist/css/bootstrap.css
```

### structure
```
dist
bower_components
src
    scripts
    css
```

### site.css
```
@import url('../../bower_components/bootstrap/dist/css/bootstrap.css');
```

### config
```
{
    appDir: 'src',
    baseUrl: 'scripts',
    dir: 'dist',

    logLevel: 1,

    optimize: 'none',
    mainConfigFile: 'src/scripts/main.js',

    modules: [
      {
        name: 'bootstrap',
        include: ['requirejs'],
        exclude: ['app'],
        create: true
      },
      {
        name: 'app',
        include: ['boot'],
        excludeShallow: ['requirejs']
      }
    ],
    // still getting bootstrap css files deleted as at v2.1.16
    // see: https://github.com/jrburke/requirejs/issues/755
    removeCombined: true,
  }
```
