### ISSUE TITLE
Multiple require.js contexts and optimize

### ISSUE THREAD

**Issue by ghost** [requirejs/requirejs#764]
Hello,

I have an app that uses multiple context of require.js.
I have a mainContext, which is most of my app, and some other contexts I need to interact with.

When running the optimizer, I got the error :
Error: The build argument "context" is not supported in a build. It should only be used in web pages.

How should I go for having multiple require.js contexts in my app and still being able to use the optimizer ?

**Comment by twizzyyanki** [comment]
Is this still an issue or has something be done about this in newer versions of requireJS?

**Comment by Malharhak** [comment]
I think there is a feature for submodules or something on require.js now, which would be used for that kind of situations, I heard of it a while ago. Didn't try it though.
