### ISSUE TITLE
New Feature: Set BaseUrl with a Data Attribute

### ISSUE THREAD

**Issue by nfplee** [requirejs/requirejs#773]
My application sets the baseUrl dynamically. This way I can easily configure my script files to move them to a CDN in the future. The only way I have found to do this is to say:

``` JavaScript
<script>
    var require = {
        baseUrl: '/Assets/'
    };
</script>
<script data-main="Scripts/main" src="/Assets/Scripts/require.js"></script>
```

Note: Both occurrences of "/Assets/" would be from server side variable e.g. in PHP $assets_url.

I have to do this at the top of all my files I require some scripting and it's becoming quite tedious. I'd like to be able to simply say:

``` JavaScript
<script data-base-url="/Assets/" data-main="Scripts/main" src="/Assets/Scripts/require.js"></script>
```

I'd appreciate your thoughts on this idea. Thanks

**Comment by karolyi** [comment]
+1
