### ISSUE TITLE
Paths fallback not supported in optimizer?

### ISSUE THREAD

**Issue by farmersmc** [requirejs/requirejs#791]
I am running the Yeoman Beta 6, having installed require.js using the Webapp scaffolding. I am currently having build issues trying to build using Grunt.

I have updated the require.config function:

``` require.config({
    paths: {
        jquery: [
            // jQuery Fallback - http://requirejs.org/docs/api.html#pathsfallbacks
            '//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min',
            // If the CDN location fails, load from this location
            '../bower_components/jquery/jquery'
        ],
        bootstrap: 'vendor/bootstrap'
    },
    shim: {
        bootstrap: {
            deps: ['jquery'],
            exports: 'jquery'
        }
    }
});
```

When I am in the directory and run "grunt" in the Terminal, when it gets to the requirejs:dist step, I receive the following error:

```
[Error: Error: paths fallback not supported in optimizer. Please provide a build config path override for jquery
    at /Users/myaccount/Sites/test/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:24325:23
]
```

Is there an error in the way I've formatted the path fallback?

**Comment by safakgur** [comment]
I've recently failed in all the above and asked [this question](http://stackoverflow.com/q/42527949/704144) on SO.
