### ISSUE TITLE
Trouble optimizing with TweenMax

### ISSUE THREAD

**Issue by johnmastri** [requirejs/requirejs#803]
Hello all,

I've retrofit a project to use require.js.  When I optimize using r.js and rhino, I get a min file with no errors.  However when I load the app using the .min file, I get an error saying "cannot call the method 'to' of undefined".  The method 'to' belongs to TweenMax.  When I load the app using the non-optimized code, it works no problem.  

Here is the log from the terminal when running r.js:

Tracing dependencies for: ../js/main
Cannot optimize network URL, skipping: http://a.vimeocdn.com/js/froogaloop2.min.js
Uglifying file: /Users/---/prototype/js/main.min.js
Users/---/prototype/js/main.min.js
Users/---/prototype/js/libs/requirejs/require.js
Users/---/prototype/js/libs/jquery/jquery-1.7.1.min.js
Users/---/prototype/js/libs/underscore/underscore-amd.js
Users/---/prototype/js/libs/backbone/backbone-amd.js
Users/---/prototype/js/libs/greensock/uncompressed/TweenMax.js
Users/---/prototype/js/libs/greensock/uncompressed/plugins/CSSPlugin.js
Users/---/prototype/js/akinsparker/views/APVideoView.js
Users/---/prototype/js/text.js
text!templates/ProfileElement.html
Users/---/prototype/js/akinsparker/views/ProfileElementView.js
text!templates/CollagePiece.html
Users/---/prototype/js/akinsparker/views/CollagePieceView.js
text!templates/ProjectPiece.html
Users/---/prototype/js/akinsparker/views/ProjectPieceView.js
Users/---/prototype/js/akinsparker/APHelper.js
Users/---/prototype/js/akinsparker/router/Workspace.js
Users/---/prototype/js/libs/isotope/jquery.isotope.js
Users/---/prototype/js/akinsparker/views/ProjectView.js
Users/---/prototype/js/libs/imagesloaded/jquery.imagesloaded.js
Users/---/prototype/js/akinsparker/views/APMainView.js
Users/---/prototype/js/libs/mCustomScrollbar/uncompressed/jquery.mCustomScrollbar.js
Users/---/prototype/js/libs/mCustomScrollbar/uncompressed/jquery.mousewheel.js
Users/---/prototype/js/akinsparker/models/CollageElement.js
Users/---/prototype/js/akinsparker/collections/APCollageCollection.js
Users/---/prototype/js/akinsparker/models/ProfileElement.js
Users/---/prototype/js/akinsparker/collections/APTeamCollection.js
Users/---/prototype/js/app.js
Users/---/prototype/js/../js/main.js

Here is a link to all the code including the build folder which houses my build settings.

https://www.dropbox.com/sh/oyepi7n1kwqrzmr/QS94f_UtfR

At this point this is beyond my level of understanding so any advice would be greatly appreciated!

Thanks!

**Comment by badoubadou** [comment]
Hi, I have the same problem, it's closed, but can someone explain me how lagden solution work ? because I can't figure out how to apply it to my project. I'm using use-init. 
thanks.

**Comment by lagden** [comment]
@badoubadou Now a days the GSAP >= 015.1 lib works fine...

**config.js** sample:

```javascript
/* global define, requirejs */

'use strict';

define('config', function() {
  requirejs.config({
    waitSeconds: 10,
    baseUrl: '/js/lib',
    paths: {
      'app': '../app',
      'templates': '../templates',

      'facebook': '//connect.facebook.net/pt_BR/all',

      'TimelineLite': './gsap/src/uncompressed/TimelineLite',
      'TweenLite': './gsap/src/uncompressed/TweenLite',
      'Draggable': './gsap/src/uncompressed/utils/Draggable',
      'ScrollToPlugin': './gsap/src/uncompressed/plugins/ScrollToPlugin',
      'CSSPlugin': './gsap/src/uncompressed/plugins/CSSPlugin',
    },
    shim: {
      'facebook': {
        exports: 'FB'
      }
    }
  });
});
```

your **module.js**:

```javascript
/* global define */

'use strict';

define([
  'TweenLite',
  'Draggable',
  'CSSPlugin'
], function (TweenLite, Draggable, CSSPlugin) {

  var el = document.querySelector('#el');
  TweenLite.set(el, { x: 10 });

  //...
});
