### ISSUE TITLE
can auto load the *.min.js version?

### ISSUE THREAD

**Issue by mwc** [requirejs/requirejs#807]
add a configuration such as “autoUseMin" ?????

How can I tell RequireJs to load my minified files instead of my original script files ?

**Comment by joelharkes** [comment]
Please reconsider this. 

im using require.js in a dynamic web environment where plugins with extra javascript may be loaded in. I can't pre optimize the javascript so i'm using this method.

I want it to take the min.js in production environments

**Comment by wikola** [comment]
This question isn't fresh but I am on hold project where we can't use r.js, so I use [Fine grained URL control](http://requirejs.org/docs/optimization.html#onejs)

```
if (!debug) {
	var load = requirejs.load;
	requirejs.load = function (context, moduleId, url) {
		//modify url here, then call original load
		let splited = url.split('.');
		if (splited[splited.length - 1] === 'js' && splited[splited.length - 2] !== 'min') {
			splited[splited.length - 1] = "min.js";
			url = splited.join('.');
		}
		return load(context, moduleId, url);
	};
}

```
