### ISSUE TITLE
r:js: Nested UMD modules do not work in optimizer

### ISSUE THREAD

**Issue by andrehaveman** [requirejs/requirejs#883]
We have a module that is build with browserify as a standalone UMD module. This module contains another UMD module (https://github.com/caolan/async). When this module is used in a requirejs project, the optimizer gives the following message:

`... has more than one anonymous define. May be a built file from another build system like, Ender. Skipping normalization.`

In the browser the following error occurs:

`Uncaught Error: Mismatched anonymous define() module:`

The cause is the anonymous define call inside the UMD definition of async.js. 

Shouldn't r.js be able to ignore these define calls, when nested in another UMD module?

**Comment by teohhanhui** [comment]
Perhaps it needs to handle more (edge?) cases, such as https://github.com/cujojs/when/issues/359
