### ISSUE TITLE
provide support for es6-module-transpiler output

### ISSUE THREAD

**Issue by ryanflorence** [requirejs/requirejs#923]
see https://github.com/square/es6-module-transpiler/issues/69

tl;dr: es6 supports named and default exports, mimicking this in AMD is semantically different, future hostile and can lead to subtle bugs.

Would be great if requirejs could understand how to use the ['default'] property the transpiler spits out.

Another option is to just have a different tool wrap the modules and let requirejs remain agnostic.

**Comment by GordonSmith** [comment]
I know this thread is a bit old and I suspect the transpilers never set the __esModule flag.  But now that they are the following is a possible workaround (and would be great if it was added to requireJS as a default?)
```
        function es6Require(deps, callback, errback) {
            return require(deps, function (objs) {
                for (var i = 0; i < arguments.length; ++i) {
                    arguments[i] = arguments[i].__esModule && arguments[i].default ? arguments[i].default : arguments[i];
                }
                callback.apply(this, arguments);
            }, errback);
        }
```

Type of thing?
