### ISSUE TITLE
Mix requirejs modules and simple <script> tags while page loading

### ISSUE THREAD

**Issue by LMnet** [requirejs/requirejs#947]
I have this code in my html file:

``` html
<!-- load requirejs, config and start file -->
<script src="js/libs/requirejs/require.js"></script>
<script src="js/requireConfig.js"></script>
<script src="js/application/admin/common.js"></script>

<!-- loading some less files -->

<!-- less compiller -->
<script src="//rawgithub.com/less/less.js/master/dist/less-1.5.0.min.js" type="text/javascript"></script>
```

I separate requirejs, config and started file because I have different sections in my projects and this is the best solution for me. All works fine. But sometimes I've seen error in js console in this code:

``` js
require(['jquery'], function($){
    $(function(){
        ...
```

The error was something like I'm trying to use object as function. But sometimes it works fine. 
After some time I spent on the research of the problem, I noticed, that this problem caused by asynchronous script calls: sometimes less.js loaded faster than jquery. And requirejs recognized less.js as jquery. 
The main problem consists in the completeLoad method (line 1507). Precisely, in this place:

``` js
if (args[0] === null) {
    args[0] = moduleName;
    //If already found an anonymous module and bound it
    //to this name, then this is some other anon module
    //waiting for its completeLoad to fire.
    if (found) {
        break;
    }
    found = true;
} else if (args[0] === moduleName) {
    //Found matching define call for this script!
    found = true;
}
```

When less.js loads faster, than jquery, args[0] === null is true, so, insted of use real jquery as jquery module, this method use less as jquery module. 
I think this problem occurred, because less.js isn't loaded as requirejs module.

**Comment by jinty** [comment]
for anyone else dealing with this issue, https://github.com/jinty/requirejs/commit/5776e23944129a8a67e2741e2f2036590cb8eed6 is my attempt to make it less acute. Not proposing as a pull request as it does suppress the "Mismatched" error which has already been rejected (see https://github.com/jrburke/requirejs/pull/1354)

**Comment by DanielHreben** [comment]
That's how I fucking solve it:
```html
<script>
  try {
    __backup = { define, require, requirejs }
    define = undefined
    require = undefined
    requirejs = undefined
  } catch (e) {
    __backup = {}
  }

</script>

<script src="https://unpkg.com/react@15/dist/react.min.js"></script>
<script src="https://unpkg.com/react-dom@15/dist/react-dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.30.8/react-bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-router/3.0.1/ReactRouter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js"></script>

<script>
  Object.assign(window, __backup)
</script>
```
