### ISSUE TITLE
Plugin loading exports

### ISSUE THREAD

**Issue by leog** [requirejs/requirejs#997]
Hi all. 

I just wanted to know if this is possible somehow with RequireJS.

Let's say I want to make a plugin that loads modules which exports a string. I want to create a plugin that applied to more than one module grabs the module's strings and perhaps extends RequireJS to have a new function (like toUrl) to get a list of those strings.

Something like this:

```
require([
  'plugin!path/to/mod_exports_a',
  'plugin!path/to/mod_exports_b',
  'plugin!path/to/mod_exports_c'
], function() {
  console.log(require.getStrings()) // Logs ["a", "b", "c"] 
})
```

I don't want to handle those strings as function arguments because I may have quite a few of those modules, which may not be scalable.

Thanks a lot in advance.

PS: I was thinking of using "arguments" but is such an ugly solution that I hope this can be done with a RequireJS plugin.

**Comment by leog** [comment]
Hi @jrburke,

Going back to this, is there a way I could store information somewhere on RequireJS for a module ID in order to implement my original request?

I've been trying to make it work but somehow I can't get to store whatever I want on an object for a module, much like the ```config``` part of RequireJS.config.

Thanks in advance.

**Comment by jrburke** [comment]
You could create a window global to store the values, but I do not suggest that as it defeats one of the main advantages of modules, their isolation. Similar issues with putting it on a requirejs config, it breaks the encapsulation.

You could define a 'groupedModules' module that just did:

```javascript
// In groupedModules.js
define(function(require) {
  return: {
    a: require(plugin!'a'),
    b: require('plugin!b'),
    c: require('plugin!c')
  };
});
```
Then in a dynamic require call:

```javascript
require(['groupedModules'], function(g) {
    g.a;
    g.b;
});
```

**Comment by leog** [comment]
Thanks @jrburke, I'm actually doing that right now. I just wanted to simplify the code trying to encapsulate the whole thing into a single plugin avoiding repetitive and boilerplate code. 

I assume that there is no chance to use RequireJS the way I want to, right?

Anyway, thanks for looking into this.

Regards.
